### ISSUE TITLE
Ctrlp opens new file

### ISSUE THREAD

**Issue by mhartington** [ctrlpvim/ctrlp.vim#105]
In neovim and vime, I'm getting this odd issue

If you try to open a file, it will cut the path name, so 

`"js/angular/controller/headerBarController.js" [New DIRECTORY]`

becomes

`"ular/controller/headerBarController.js" [New DIRECTORY]`

Not sure if this is known. Here is the configuration for ctrlp in my `.nvimrc`

```viml
let g:ctrlp_user_command = 'ag %s -i --nogroup --hidden
    \ --ignore .git
    \ --ignore .svn
    \ --ignore .hg
    \ --ignore .DS_Store
    \ --ignore "**/*.pyc"
    \ --ignore lib
    \ -g ""'
  let g:ctrlp_regexp = 1
  let g:ctrlp_use_caching = 0
  let g:ctrlp_working_path_mode = 0
  let g:ctrlp_switch_buffer = 0
```

**Comment by mattn** [comment]
after getting fail, could you try to type `:pwd`?

**Comment by nirum** [comment]
I get the same error using Macvim. When I check the directory with `pwd`, it's the same directory as before.  I think possible a very recent commit is possibly the cause, because I keep plugins updated through vim-plug

**Comment by mattn** [comment]
hmm, I can't reproduce it.

**Comment by mattn** [comment]
if you use find instead of ag, you'll get same?

**Comment by mhartington** [comment]
>after getting fail, could you try to type :pwd?

This does return the correct path. 

>if you use find instead of ag, you'll get same?

If I use the built in search from ctrl-p, it produces the same error.

**Comment by mattn** [comment]
> If I use the built in search from ctrl-p, it produces the same error.

your vimrc seems having some settings that affect to ctrlp maybe. could you figure out which settings is wrong?

**Comment by nirum** [comment]
After stripping down my vimrc and trying things one at a time, I've localized the error to one plugin: the [vim-devicons plugin](https://github.com/ryanoasis/vim-devicons).  @mhartington do you also have this plugin enabled?

When I disable that plug-in, the bug goes away.  Also, it looks like they recently added Ctrl-P support in [this commit](https://github.com/ryanoasis/vim-devicons/commit/48543fae7f07229fa532d9221e23c3574e00db90), which is maybe what is causing the bug.

**Comment by nirum** [comment]
Looks like the vim-devicons folks already know about the bug: https://github.com/ryanoasis/vim-devicons/issues/80

**Comment by ryanoasis** [comment]
Yep this is totally ryanoasis/vim-devicons#80 , there is a workaround as @nirum mentioned.

I have yet to replicate this personally _but_ now multiple people have run into this so it should not be too hard to replicate, i'll need to redouble my efforts :blush: 

Apologies :worried:

**Comment by ryanoasis** [comment]
@mhartington, @nirum this should be properly fixed now in https://github.com/ryanoasis/vim-devicons let me know if pulling latest [v0.5.1](https://github.com/ryanoasis/vim-devicons/releases/tag/v0.5.1) version resolves for you

@nirum thanks for the cross project reference

**Comment by mhartington** [comment]
Looks good to me. Thanks @ryanoasis

**Comment by nirum** [comment]
works for me too. thanks!
