### ISSUE TITLE
alternate buffer is not the default selection for :CtrlPBuffer when neovim terminal buffer exists

### ISSUE THREAD

**Issue by bmedicke** [ctrlpvim/ctrlp.vim#106]
Normally the alternate buffer (last used buffer, marked with `#`) is the default selection for `:CtrlPBuffer` which allows for very fast and predictable switching between two buffers. When using a neovim terminal buffer (`term://`) it is selected instead.

**Comment by mattn** [comment]
Sorry, I'm not using neovim. anyone. cound you please handle this issue?

**Comment by tacahiroy** [comment]
Indeed, I've reproduced the issue. will have a look

**Comment by kballenegger** [comment]
`term://` buffers don't seem to be showing up at all in my CtrlP setup. Wondering if this is related…
