### ISSUE TITLE
Option g:ctrlp_mruf_default_order does nothing, probably deprecated

### ISSUE THREAD

**Issue by lervag** [ctrlpvim/ctrlp.vim#108]
It seems that the option `g:ctrlp_mruf_default_order` has been removed, except from the documentation.

**Comment by mattn** [comment]
No. it's not removed.

https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L78

**Comment by lervag** [comment]
Sorry, my mistake!

**Comment by mattn** [comment]
no prob :)
