### ISSUE TITLE
Undefined variable on multiple commands

### ISSUE THREAD

**Issue by jsmith29** [ctrlpvim/ctrlp.vim#115]
Hi! I've been trying to change my default .cache directory since I don't like seeing that in my user folder (Win7 64bit) but for some reason "let g:ctrlp_cache_dir" and many other commands don't work; they also don't appear when I try to TAB to scroll available commands.
CtrlP works without any problems, it's just that I cannot use some commands and I don't know why. At first I had Pathogen and I thought that was the problem, so I installed the plugin manually, every folder/file in the right place, but that didn't fix it.
I feel the answer is really simple, but I just can't figure it out, so I need some help please. :)

**Comment by mattn** [comment]
What mean of title of this issue?

**Comment by jsmith29** [comment]
E121: Undefined variable: g:ctrlp_cache_dir
Commands I can use: ctrlp, ctrlp_alldirs, ctrlp_allfiles, ctrlp_allmixes, ctrlp_alltags, ctrlp_buftags, ctrlp_builtins, ctrlp_cmd, ctrlp_ext_vars, ctrlp_lines, ctrlp_map, ctrlp_mruf_case_sensitive, ctrlp_mruf_exclude, ctrlp_mruf_include, ctrlp_mruf_max, ctrlp_mruf_relative, ctrlp_mruf_save_on_update.
The rest I cannot use.I get the error E121. (the options in :help ctrlp-options)
I only want to use "let g:ctrlp_cache_dir" to change the ".cache" folder location.

**Comment by mattn** [comment]
* What version of vim do you use?
* What OS do you use?
* How to reproduce it?
* What way to install did you do?

**Comment by jsmith29** [comment]
Nevermind, I figured it out. I knew it was something simple and it was. I was misspelling the path on Windows7. I managed to change my cache dir.
I thought there was something wrong with the command options because I couldn't see them when I was using TAB to scroll, but it's no issue, they work.
Thank you for the quick replies, and have a nice day! :)

**Comment by mattn** [comment]
No Problem. :)
