### ISSUE TITLE
Not finding correctly

### ISSUE THREAD

**Issue by Goddard** [ctrlpvim/ctrlp.vim#121]
I have a file on path templates/index.php

but when I type templates/index.php it shows a bunch of paths with similar names, but not the one I am actually searching for, at least at the top of the list.  

Shouldn't it display exact matches?

I'm new to vim btw.

**Comment by elben** [comment]
Check out this issue: https://github.com/ctrlpvim/ctrlp.vim/issues/69

**Comment by mattn** [comment]
dup #69
