### ISSUE TITLE
CtrlP not finding files

### ISSUE THREAD

**Issue by lukeberry99** [ctrlpvim/ctrlp.vim#123]
I'm having a strange issue where CtrlP is not finding certain files.

This is my folder structure

-app
-components
--Github
---UserProfile.js
---Repos.js
--Notes
---Notes.js
-Main.js
-Home.js
-Profile.js

CtrlP can find app/components/Notes/Notes.js but it can't find anything in app/components/Github?

How is this possible?  I've attached a Gif showing what I mean.

Trying F5 and CtrlPClearAllCaches does not seem to of helped

![ctrlp](https://cloud.githubusercontent.com/assets/1644147/9531456/e99f8efc-4cfd-11e5-9f1b-d06d0bdf85a5.gif)

**Comment by mattn** [comment]
dup #69
