### ISSUE TITLE
Extend ctrlp_custom_ignores in project specific .vimrc

### ISSUE THREAD

**Issue by qstrahl** [ctrlpvim/ctrlp.vim#124]
From kien/ctrlp.vim#671:

> Is there any way to extend or append the ctrlp_custom_ignores in a project specific .vimrc.
> 
> I'd like to have commonly ignored folder patterns ignored in main .vimrc and then add project specific ignores on top of that in the project .vimrc.
> 
> I'm currently just using wildignore which handles this I presume with += but not sure what depth of scope in vim this sets the ignore to.
> 
> I'd really just like to have this available specific to ctrlp??

And my reply:

> What would be nice is if ctrlp first checked if `b:ctrlp_custom_ignores` exists before looking at `g:ctrlp_custom_ignores` -- this would allow for buffer-specific configuration. The same technique could be applied to any option for which that makes sense.

**Comment by ludovicchabant** [comment]
I have a prototype of something like this over here: https://github.com/ludovicchabant/vim-ctrlp-autoignore

It's a standard CtrlP extension so just enabled it with `g:ctrlp_extensions`. Once enabled, it lets you add a `.ctrlpignore` file at the root of your project. On regexp per line. Anything that matches will be ignored in that project.

/cc @jamesscholeyweb

**Comment by ludovicchabant** [comment]
Actually, I meant to ping @d11wtq and @mattn about this extension, maybe it would deserve being shipped in the official plugin.

**Comment by jamesscholeyweb** [comment]
Thanks for that Ludovic. Seems to make sense to me that it should be a core functionality rather than a separate extension. I am aware this can already be achieved with just ctrlp as outlined in kien/ctrlp.vim#671 , But a simple .ctrlpignore would be nice.

**Comment by mattn** [comment]
LGTM, lets merge into core with disable default.

**Comment by ludovicchabant** [comment]
ok I'll make a new PR for it, and when it's done I'll close this issue.

**Comment by ludovicchabant** [comment]
Ok, the PR is up here: https://github.com/ctrlpvim/ctrlp.vim/pull/155

**Comment by qstrahl** [comment]
Closing since addressed in #155
