### ISSUE TITLE
what is the difference between this repo and kien's?

### ISSUE THREAD

**Issue by wsdjeg** [ctrlpvim/ctrlp.vim#132]
i am just changeing kien/ctrlp.vim to ctrlpvim/ctrlp.vim,is there any diff between them?

**Comment by raventid** [comment]
This repository is supposed to be supported. So you can expect updates, bug fixes and help from the community. It is not as actively supported, as it might be, however I recommend you to use this ctrlp.

**Comment by wsdjeg** [comment]
Thank you, I understand ,i will use this ctrlp!
