### ISSUE TITLE
How to set default search directory?

### ISSUE THREAD

**Issue by wolfv6** [ctrlpvim/ctrlp.vim#135]
ctrlp searches my home directory. Is there a line I can put in vimrc so that ctrlp only searches the ~/Documents directory by default?

Thank you.

**Comment by captbaritone** [comment]
ctrlp derives it's search path from the currently open file. More info here: https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L181-L198

**Comment by wolfv6** [comment]
Thanks captbaritone.
I added this line to my vimrc, and it works:

    cd /home/me/Documents/
