### ISSUE TITLE
Can't find any entries when the path contains spaces

### ISSUE THREAD

**Issue by OskarPersson** [ctrlpvim/ctrlp.vim#138]
I'm having problems with CtrlP since upgrading to Vim 7.4. 

CtrlP can't find any entries in some folders, this problem didn't occur before upgrading.

I think that the problem is that the path have spaces in it. Though this weren't a problem before upgrading from the built-in Vim in OS X (El Capitan). If I rename the folders in the path so that there are no spaces, then I don't have the problem anymore. But this shouldn't be required.

My `vim.rc`:

```
" -------- Vundle -------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
```

I upgraded using `brew install vim` and this is what `vim --version` says:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  1 2015 17:36:26)
MacOS X (unix) version
Included patches: 1-884
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -F/private/tmp/vim20151001-44506-3ot6hp/vim-7.4.884/Frameworks -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```

**Comment by tacahiroy** [comment]
hmm - I don't reproduce the problem what you reported.
```console
% vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 30 2015 21:24:51)
MacOS X (unix) version
Included patches: 1-712
```

ctrlp finds files/dirs correctly with the above Vim and your configuration (vim.rc).
I've tested with the situation below:
```console
% ls -R
.:
foo/

./foo:
README.txt  bar/  fi le.txt

./foo/bar:
baz/

./foo/bar/baz:
Program Files/

./foo/bar/baz/Program Files:
a.txt  b.txt  c.txt
```

Is that `vim.rc` your entire configuration?

**Comment by OskarPersson** [comment]
> Is that vim.rc your entire configuration?
Yes.

Where and how did you install your Vim? Note that I'm using

**Comment by tacahiroy** [comment]
> Where and how did you install your Vim? Note that I'm using
I use HomeBrew'ed Vim and located /usr/local/opt/macvim/MacVim.app/Contents/MacOS/Vim.
And it's running on the same OS as yours, OS X 10.11, the issue is unlikely to be happened.

I still have no idea why it's happening on your env. will dig into deeper

**Comment by OskarPersson** [comment]
I did some more testing, maybe its not the spaces after all. Can you try the following path?

```
åäö/foo/bar:

baz.txt
```

while standing in `åäö`?

**Comment by tacahiroy** [comment]
Tested with homebrew'ed vim / macvim and it worked ok even if there are directories which contains non-ascii characters in its name.

**Comment by cskr** [comment]
I face this issue too. I see the following error, when using ctrlp for the first time after starting vim in a directory containing spaces in its name.

```
Error detected while processing function ctrlp#init[31]..<SNR>34_setlines_post[6]..ctrlp#files[8]..<SNR>34_GlobPath:
line    3:
E484: Can't open file /home/cskr/foo\ bar
```

Subsequently, ctrlp does not list any file in that session. I find that changing [this line](https://github.com/ctrlpvim/ctrlp.vim/blob/971c4d4/autoload/ctrlp.vim#L389) to `cal s:GlobPath(s:dyncwd, 0)` fixes the issue. I don't know vimscript enough to judge the safety of such a change, but hoping that it helps someone identify the root cause.

**OS:** Debian unstable
**VIM Version:** 8.2.2367
**Ctrlp Version:** 1.81 (971c4d4)

**Comment by tacahiroy** [comment]
I still don't reproduce the problem with the following set up.
* OS: Ubuntu-20.04 on WSL2
* Vim: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 24 2021 23:04:52) Included patches: 1-2401
* ctrlp.vim: 971c4d4

ah - finally I successfully reproduced the issue.
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function ctrlp#init[31]..<SNR>122_setlines_post[6]..ctrlp#files[8]..<SNR>122_GlobPath:
line    3:
E484: Can't open file /home/tacahiroy/a/c\ d
```

The problem is actually caused if the current directory contains a whitespace in its name.
E.g. `/home/foo/a/b c`

will debug this.

**Comment by tacahiroy** [comment]
I have made a modification to fix the issue. But it's not fully tested yet, so is in WIP atm.

**Comment by brodzik** [comment]
Me too:
![2021-11-15_15-25-11](https://user-images.githubusercontent.com/5142377/141798318-ec3a4e37-eecb-4e3a-bac0-f7ef55656b52.png)

**Comment by mattn** [comment]
Please show me whole part of errors.

**Comment by cskr** [comment]
This patch fixes it for me.

**Comment by gadamiak** [comment]
Looks to be fixing for me as well.
