### ISSUE TITLE
why vim can not find the command ag!

### ISSUE THREAD

**Issue by wsdjeg** [ctrlpvim/ctrlp.vim#141]
i can run ag in terminal
![2015-10-13 23-23-59](https://cloud.githubusercontent.com/assets/13142418/10459314/92a258cc-7201-11e5-990d-05924d87772a.png)
i can use ctrilp in ~/javautils
![2015-10-13 23-23-44](https://cloud.githubusercontent.com/assets/13142418/10459332/aa61341a-7201-11e5-8adf-deb0b27905d0.png)
but in the dir ~/android-sdk-linux get the error
![2015-10-13 23-23-26](https://cloud.githubusercontent.com/assets/13142418/10459351/c0d1f798-7201-11e5-9640-3de7455be673.png)

**Comment by tacahiroy** [comment]
Please make sure `$PATH` contains a directory `ag` located.
`:echo $PATH`

**Comment by wsdjeg** [comment]
not my path's problem ,i have fixed it by chanage my vimrc
