### ISSUE TITLE
[SOLVED]How can i only search files or buffers using one command without mru files?

### ISSUE THREAD

**Issue by Treri** [ctrlpvim/ctrlp.vim#142]
Now searching files and searching buffer are two commands. `CtrlP` and `CtrlpBuffer`

I know there is a `CtrlPMixed`, but this is also include mru files.

How can I only search files which is opened or not opened in one project using one command, not mru files?

**Comment by tacahiroy** [comment]
AFAIK, ctrlp doesn't provide like that option.
If those files are in one project, `CtrlP` just works for you.

**Comment by Treri** [comment]
@tacahiroy Thanks very much. `CtrlP` is what I want. 😊
