### ISSUE TITLE
can you please list all the plugins which can work with ctrlp?

### ISSUE THREAD

**Issue by wsdjeg** [ctrlpvim/ctrlp.vim#144]
https://github.com/Shougo/unite.vim/wiki/unite-plugins

here is unite's plugin

**Comment by mattn** [comment]
I enabled wiki.

https://github.com/ctrlpvim/ctrlp.vim/wiki/ctrlp-plugins

we can't close this issue until someone put on there. So closing this issue after for a while.
Anyone, please put plugins you favorite.

**Comment by wsdjeg** [comment]
OK，l will try to give PR to the wiki

**Comment by mattn** [comment]
You can modify wiki without PRs :)
