### ISSUE TITLE
ctrlp_user_command doesn't use aliases

### ISSUE THREAD

**Issue by dxu** [ctrlpvim/ctrlp.vim#146]
I have a custom alias for ag to set the location of the .agignore, but when I run ag as the ctrlp_user_command, it doesn't work. 

I've also tested just creating aliases and trying to run them as commands in the ctrlp_user_command. 

Is this expected behavior?

**Comment by mattn** [comment]
system(2) execute `/bin/sh` not your favorite shell. and in generary, alias is not expanded in inteructive shells. if you use bash, please see the manual of expand_aliases.
