### ISSUE TITLE
CtrlPTag shows tags that aren't in the specified tags file

### ISSUE THREAD

**Issue by kriox26** [ctrlpvim/ctrlp.vim#148]
Hi! It seems that CtrlPTag shows a lot more tags than the ones that are specified in the tags file. I'm currently working on a Gem(a small one) So the tags file is pretty small. I used the following to generate the tags: `ctags -f .git/tags --tag-relative -R --languages=ruby --exclude=.git --exclude=log` . When I check the tags file, I see that it only generated files for the current project(the gem), but when I go to vim and enter `:CtrlPTag` it also adds all the tags for all my gems. I tried running `:CtrlPClearAllCaches` and it did not work. Here are some relevant(I think) configurations that I have:
```viml
set tags=.git/tags " It used to have set tags+=./git/tags
if executable('ag')
  set grepprg=ag\ --nogroup
  let g:grep_cmd_opts = '--line-numbers --noheading'
  let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --ignore ''.git'' --ignore ''.DS_Store'' --ignore ''node_modules'' --ignore ''log'' --hidden -g ""'
endif
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_max_files = 0
let g:ctrlp_max_height =  25
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn|log)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
   \}
let g:ctrlp_working_path_mode = 'rc'
```

Thanks, awesome plugin! :+1:

**Comment by tacahiroy** [comment]
Since ctrlp retrieves tags files using a Vim's built-in function `tagfiles()`, that's weird if `tags` option includes only *.git/tags*.
Can you check `:echo tagfiles()` please.

**Comment by kriox26** [comment]
Weird, it shows:
```
[ '.git/tags', '.git/Gemfile.lock.tags' ]
```
It seems that ctags created tags based on the Gemfile. Anyway, I see it's not a CtrlP issue, thanks!!!
