### ISSUE TITLE
Where is the bookmark directories list saved?

### ISSUE THREAD

**Issue by wolfv6** [ctrlpvim/ctrlp.vim#149]
Where is the Ctrl-P bookmarked directories list (:CtrlPBookmarkDir)?
I want to backup and edit it.

Ctrl-P is great, thanks for sharing it.

**Comment by tacahiroy** [comment]
By default, it's located in a directory, $HOME.'/.cache/ctrlp/bkd'.
You can change to somewhere else using a variable, g:ctrlp_cache_dir.

**Comment by wolfv6** [comment]
Thanks for the quick response.
