### ISSUE TITLE
Make the bookmarked directories list static?

### ISSUE THREAD

**Issue by wolfv6** [ctrlpvim/ctrlp.vim#150]
Every time a CtrlPBookmarkDir is used, the used bookmark moves to the bottom of the list.
Is there a way to make the bookmarked directories list static, so the order does not change?
(I edited the list to my preferred order in ~/.cache/ctrlp/bkd/cache.txt)
Or keep the bookmark list in the same order as a directory tree? (depth-first alphabetical)

Static bookmarks are easier to find than moving targets.
That's why bookmarks in web browsers are always static.
I'm not complaining; Ctrl-P is still the best.

**Comment by tacahiroy** [comment]
Unfortunately, there is no way to avoid this behaviour right now.
Probably, this aims kinda MRU bookmark or something, but yeah, I don't think it's useful either.

**Comment by wolfv6** [comment]
Thank you for the quick response.
