### ISSUE TITLE
■■■■■■■■■■Technical Support■■■■■■■■■■

### ISSUE THREAD

**Issue by wsdjeg** [ctrlpvim/ctrlp.vim#151]
@mattn @d11wtq 
please do not close this issue!
i will link this issue to all the issues of ctrlp, we just need to concerned about the status of other issues!

**Comment by mattn** [comment]
I don't mind but I don't understand what is a merit of this.

**Comment by wsdjeg** [comment]
deal with their iusse and let more people use  this repo

**Comment by mattn** [comment]
Sorry, I can't understand what this have merit. If you want to know the updates or solved of this issue. please do it your self.
