### ISSUE TITLE
Problems with CPSM

### ISSUE THREAD

**Issue by LemonBoy** [ctrlpvim/ctrlp.vim#152]
When CPSM [1] is used as external matcher the ctrlp window keep showing no results at all. This happened after mindlessly updating cpsm and ctrlp at the same time some hours ago.

[1] https://github.com/nixprime/cpsm

**Comment by mattn** [comment]
Could you please show me the way to reproduce?

**Comment by LemonBoy** [comment]
My bad, it seems I didn't recompile cpsm after updating it last night.
It seems the python stub exits early due to an undefined symbol that should be exported by libICU.
