### ISSUE TITLE
Backspace on empty prompt to close Ctrlp?

### ISSUE THREAD

**Issue by WscriChy** [ctrlpvim/ctrlp.vim#156]
From an old [issue](https://github.com/kien/ctrlp.vim/issues/610)

Is it possible to have backspace on an empty prompt exit the ctrlp prompt?

How can you detect the input in a prompt after a function is called via the ctrlp buffer?

**Comment by wsdjeg** [comment]
backspace is used for delete the input char,i think it is not a good idea to use it close ctrlp,maybe you can use esc,and it works well now

**Comment by WscriChy** [comment]
Yes, maybe you are right, it will interfere with users who are used to press backspace to delete all their input, then they accidentally could close the CtrlP instance. But if it is possible to add it as an optional feature for people who like to use it for quitting it might be quite popular.

**Comment by wsdjeg** [comment]
i have try with imap or map ,but it does not work.
