### ISSUE TITLE
let g:ctrlp_cmd = 'CtrlPMixed'

### ISSUE THREAD

**Issue by mooreniemi** [ctrlpvim/ctrlp.vim#157]
I might be misunderstanding, but I thought if I set `let g:ctrlp_cmd = 'CtrlPMixed'` in my `.vimrc` then the default behavior of CtrlP would be to open the mixed searcher, but it continues to just open the normal one. Is there a way I can achieve this?

**Comment by tacahiroy** [comment]
`g:ctrlp_cmd` defines a command to be invoked if you press a key combination that specified with `g:ctrlp_map`.
So it nothing affects for `CtrlP` command.

See `:h 'g:ctrlp_cmd'`

**Comment by mattn** [comment]
@mooreniemi if you want to change default behavior of `CtrlP`, please specify `g:ctrlp_map`, `g:ctrlp_cmd` both.

**Comment by mooreniemi** [comment]
Ahh ok, I just assumed since I hadn't changed the default of `ctrlp_map` (`<C-P>`) it would overwrite it for me. Makes sense! Thanks all.
