### ISSUE TITLE
How to open in current buffer?

### ISSUE THREAD

**Issue by hasenj** [ctrlpvim/ctrlp.vim#163]
If I have a file open in another tab, ctrlp will redirect me to the already existing tab.

Is there a way to force it to just open the file in the current tab/split instead of just switching to the existing buffer?

**Comment by wsdjeg** [comment]
please use c-o which means open then type r that means replease

**Comment by wsdjeg** [comment]
and you can create a autocmd buffer map

**Comment by thefron** [comment]
@wsdjeg In my case, even chosing [r]eplace opens left top split instead of current buffer. Do you have any idea?

**Comment by tacahiroy** [comment]
Basically, you can use an option called `g:ctrlp_switch_buffer` to achieve that, the option doesn't work expectedly though (#169).

**Comment by tacahiroy** [comment]
closing
