### ISSUE TITLE
How to fix kein/ctrlp.vim deprecate message 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ctrlpvim/ctrlp.vim#165]
kein/ctrlp.vim is deprecate I changed Plugin file from `Plug 'kien/ctrlp.vim'` to `Plug 'ctrlpvim/ctrlp.vim'` and typed `nvim +PlugInstall` but nothing seem to happen. I still get the below warning. Any idea? 

I am using https://github.com/nicknisi/dotfiles that is why I have different Plugin file and not the begin/end function in vimrc file. 

~
❯ vim
vim-devicons: https://github.com/kien/ctrlp.vim is deprecated since v0.7.0, please use https://github.com/ctrlpvim/ctrlp.vim
Press ENTER or type command to continue

**Comment by wsdjeg** [comment]
can you try with rm -rf ~/.vim/plugged/ctrlp.vim and then reinstall the plugin!

**Comment by ryanoasis** [comment]
Just stumbled upon this. Will take a look, problem is likely on my end :blush:
