### ISSUE TITLE
How to make the regex in -G opetion case insensitive?

### ISSUE THREAD

**Issue by d0u9** [ctrlpvim/ctrlp.vim#167]
I know in some languages, `/regx/i` makes the regex become case insensitive. I tried it but doesn't work.

**Comment by tacahiroy** [comment]
Can you explain more details please.
Where you did define the command?   In `g:ctrlp_user_command`?

**Comment by d0u9** [comment]
I want to find all the files which have the `txt` and `TXT` extension name though `-G` option. I can do this via `ag . -l -g "" -G "\.(txt|TXT)$"`. However, I think maybe there exist a better way such as `"\.txt$\i"`, which is a php style regex, that can be case insensitive.

**Comment by wsdjeg** [comment]
why don's use `ag -i`
it is not issue of ctrlp,you can set you self comand!
![2015-11-30 21-16-29](https://cloud.githubusercontent.com/assets/13142418/11472463/b49c928c-97a7-11e5-9466-159421c477cf.png)

**Comment by wsdjeg** [comment]
![2015-11-30 21-17-43](https://cloud.githubusercontent.com/assets/13142418/11472477/d1da6f54-97a7-11e5-97f2-45c3fa3f96e3.png)

**Comment by wsdjeg** [comment]
you also can get more help from 
https://github.com/ggreer/the_silver_searcher

**Comment by d0u9** [comment]
@wsdjeg Bingo, Thx for your help.
