### ISSUE TITLE
Open new vertical split on the right

### ISSUE THREAD

**Issue by alexfedoseev** [ctrlpvim/ctrlp.vim#171]
Hi, I haven't found anything related in docs, asking here. In my `.vimrc` I have:

```
set splitright
set splitbelow
```

I suppose it should affect how `ctrlp` opens new splits. But when I open new vertical split with `<C-v>` it opens it on the left from the current. Non-ctrlp `:vsp` and `ctrlp`'s horizontal splits works as expected.

**Comment by wsdjeg** [comment]
can you show me step by step i have trid with
1. C-w C-v split a vertical buffer
   then C-p open the ctrlp 
2. :vsp C-p 
   same as above

**Comment by alexfedoseev** [comment]
Localized the issue: it works with `:CtrlP` (opens on the right), but doesn't work with `:CtrlPBuffer` (opens on the left).

**Comment by wsdjeg** [comment]
i can not reproduce it 
here is the command i have used
:set splitright
:set splitbelow
:svp
:Ctrlp

**Comment by alexfedoseev** [comment]
I just restarted tmux session & vim and it works as expected. Closing this, sorry for the noise.

**Comment by wsdjeg** [comment]
welcome !
