### ISSUE TITLE
match window postion

### ISSUE THREAD

**Issue by chuan137** [ctrlpvim/ctrlp.vim#176]
at the moment, I use 

```
let g:ctrlp_match_window = 'bottom'
```
to control the match window either pop at the very top or very bottom

If I have multiple windows split vertically, Can it be open below the active window,
instead of very bottom?

**Comment by ludovicchabant** [comment]
Currently there's nothing to control this, no. Wouldn't you end up with the problem that your CtrlP window would be too narrow to let you see enough of the paths anyway? (unless you have a super wide screen)

**Comment by chuan137** [comment]
Thank you for replying and confirming it.

I ask because I work exclusively in vertical split. Miniizing the unfocused window automatically to zero height. Switch window rotationally with C-J, prefer to open the ctrlp window directly under the one I edit.

**Comment by ludovicchabant** [comment]
Quite unusual setup :) Either way, feel free to submit a patch if you want more options with the window position.
