### ISSUE TITLE
Doesn't show dotfiles 

### ISSUE THREAD

**Issue by tommyc38** [ctrlpvim/ctrlp.vim#184]
I updated my vimrc file per the documentation to allow for dotfiles as well as made sure that cwd was $HOME but can't see any of my dotfiles or dotdirs (e.g. .vimrc, .zshrc, .vim, etc).  Also, when I <C-J> or <C-K> through the results it doesn't scroll.  I can only see what's available on the window but know there are more results.  Any help would be greatly appreciated.

**Comment by tacahiroy** [comment]
you can use an option `let g:ctrlp_path_nolim = 1` to make the window scrollable.

**Comment by ludovicchabant** [comment]
You can also set `g:ctrlp_show_hidden` to show dot files.

**Comment by mattn** [comment]
I'll close this. If you still have problem. Please reopen this issue.
