### ISSUE TITLE
Issue with ignore files in .gitignore

### ISSUE THREAD

**Issue by LandonSchropp** [ctrlpvim/ctrlp.vim#187]
I'm a Vim newbie here, so I apologize if this is a dumb question. I'm tying to configure CtrlP to ignore files in my .gitignore file without much luck. I'm using [Thoughtbot's .vimrc file](https://github.com/thoughtbot/dotfiles/blob/master/vimrc), and I copied the following line into my .vimrc.local file from the readme:

```
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
```

When I try to open Vim, I get this error:

```
Error detected while processing /Users/landon/.vimrc.local:
line   38:
E706: Variable type mismatch for: g:ctrlp_user_command
Press ENTER or type command to continue
```

I'm using Vim 7.4.1063 and the latest version of CtrlP from [vim-plug](https://github.com/junegunn/vim-plug). Here's my full .vimrc.local file:

```
" Enable text wrapping

set textwidth=105
set formatoptions+=t
set formatoptions-=l
set linebreak
set breakindent
set breakindentopt=shift:2

" Remap the default movement keys to work with wrapped lines
nmap <buffer> <silent> k gk
nmap <buffer> <silent> j gj
nmap <buffer> <silent> 0 g0
nmap <buffer> <silent> ^ g^
nmap <buffer> <silent> $ g$

" Prevent the cursor from jumping when joining lines
nnoremap J mzJ`z

" Center the cursor when jumping positions
nnoremap n nzz
nnoremap } }zz

" Make Vim's search case-sensitive, but only when the search string contains an uppercase letter
set smartcase

" Make Y's behavior match D and C
nnoremap Y y$

" Add wildcards for CtrlP and Vim to ignore
set wildignore+=*/tmp/*,*.zip,*/build/*,*.png,*.gif,*.jpg
let g:ctrlp_custom_ignore = {
\  'file': '\v\.(zip,png,gif,jpg)$',
\  'dir': '\v(build|tmp|log)'
\ }

" Ignore .gitignore files in CtrlP
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
```

Thanks in advance!

**Comment by tacahiroy** [comment]
That's kind of basic question for Vim.
String is set to a variable `g:ctrlp_user_command` in Thoughtbot's vimrc:
https://github.com/thoughtbot/dotfiles/blob/master/vimrc#L67

You cannot assign a different type of value to a variable in Vim, so you need to `unlet` it first and then your code works.
See `:h E706` for further details.

**Comment by mattn** [comment]
I'll close this. If you still have problem. Please reopen this issue.
