### ISSUE TITLE
Option to disable unneeded modes

### ISSUE THREAD

**Issue by mcmillion** [ctrlpvim/ctrlp.vim#188]
Looking through the documentation I can't seem to find a way to disable unneeded modes. Is this possible?

I like the ability to use one binding to open CtrlP and then cycle between modes with <C-f>, but I never use some of the modes, so cycling would be faster if this list were editable. Maybe I'm missing a configuration option?

**Comment by yarray** [comment]
+1
Ideally a cycle of modes can be defined as ['buffer', 'file', 'mru'], etc., which will simultaneously limit the available modes and decide their order in the cycle.

**Comment by mattn** [comment]
Could you please try #220 ?

**Comment by yarray** [comment]
@mattn Thanks for the quick patch! It seems that it works perfectly in most cases, except when setting 'buf' as the first target.

My settings:

``` vimL
let g:ctrlp_types = ['buf', 'fil']  
```

When press ```ctrl-p```:

<img width="697" alt="2016-03-19 1 11 40_1" src="https://cloud.githubusercontent.com/assets/1227829/13885971/d6c6a38e-ed6f-11e5-8fe1-20bb7c4922da.png">

**Comment by mattn** [comment]
closed by https://github.com/ctrlpvim/ctrlp.vim/pull/220
