### ISSUE TITLE
Adding a LICENSE file at the root of the project

### ISSUE THREAD

**Issue by Spredzy** [ctrlpvim/ctrlp.vim#189]
Hello,

I am currently packaging ctrlp.vim for integration within Fedora. As part of our Guideline[1], a project should have its license file at its root. I can't seem to find the license of this project. Could you please add a LICENSE file at the root of the project ?

Thanks in advance,

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

**Comment by tacahiroy** [comment]
CtrlP is licensed by the same as Vim itself. Is is enough to add this license as the LICENSE file?
http://vimdoc.sourceforge.net/htmldoc/uganda.html
