### ISSUE TITLE
Slow startup when directory contains 3000 files (but not 3001!)

### ISSUE THREAD

**Issue by thomie** [ctrlpvim/ctrlp.vim#191]
The function `ctrlp#files` in `autoload/ctrlp.vim` [sorts](https://github.com/ctrlpvim/ctrlp.vim/blob/7f74368d85bb521951dd58123349ce66b947d058/autoload/ctrlp.vim#L371-L373) the file list on length when it has less than [compare_lim = 3000](https://github.com/ctrlpvim/ctrlp.vim/blob/7f74368d85bb521951dd58123349ce66b947d058/autoload/ctrlp.vim#L155) files. This can lead to quite a surprising user experience, where *reducing* the number of files given to ctrlp (via a custom `ctrlp_user_command`), can lead to a *slower* startup of `ctrlp`.

To reproduce:
* Put this in your .vimrc: `let g:ctrlp_user_command = 'cd %s && find . -type f'`
* Run ```mkdir files && cd files && for i in `seq 1 3001`; do touch file$i; done```
* Start vim (in the `files` directory), hit `ctrl-p`
* Notice that the file list is shown immediately
* Exit vim, delete one of the just created files
* Start vim again again, hit `ctr-p`
* Notice that it takes > 1 second before any files are shown.

The magic number `3000` (as well as the sorting of the file list) was introduced in commit b6f15390b89b74ecdd027de2f71e30658d0303bb.

I propose to disable this sorting altogether, when the file list comes in via a custom `ctrlp_user_command`. Let the user handle the sorting, if they want it.

Alternatively, expose `compare_lim` as a global option.

**Comment by twe4ked** [comment]
> I propose to disable this sorting altogether, when the file list comes in via a custom `ctrl_user_command`. Let the user handle the sorting, if they want it.

Sounds like a good plan to me.

**Comment by mattn** [comment]
https://github.com/ctrlpvim/ctrlp.vim/commit/115ee37e249cd608c51a7ee90aad43857c69d0cb

How about this? User can modify compare_lim.

**Comment by thomie** [comment]
Works for me (with `let g:ctrlp_compare_lim = 0`). Nice and snappy.
