### ISSUE TITLE
Auto accept if single match hit

### ISSUE THREAD

**Issue by renkam** [ctrlpvim/ctrlp.vim#193]
I would like to have a possibility to turn auto-accept a single match while typing.
Let's say that I have two files (for simplicity) in my project: foo.hh and foo.cc.
When I start typing 'fo' then two of them should be displayed, then after hitting 'h' key, only single match remains. After this I would like that CtrlP auto-accept this match (same way as I would hit <CR> at the moment).
Is there a simple solution for that?

**Comment by tacahiroy** [comment]
You can use 'g:ctrlp_open_single_match' to make it enables accepting automatically if there is one candidate. That's useful occasionally I think, but it makes you get annoyed if you did typo.

**Comment by tacahiroy** [comment]
no further actions. closing.
