### ISSUE TITLE
Ignore spaces when searching

### ISSUE THREAD

**Issue by uri** [ctrlpvim/ctrlp.vim#196]
I'm wondering if this is something people would be interested in. I liked being able to search for something like `pat con rb` instead of `patconrb`. My vimscript is pretty weak but if someone can point me in the right direction I'd be glad to look into this myself.

**Comment by hbradleyiii** [comment]
I was actually wondering the same thing, but it looks like this is possible by adding this to your vimrc:

```
let g:ctrlp_abbrev = {
    \ 'abbrevs': [
            \ {
                \ 'pattern': '\(^@.\+\|\\\@<!:.\+\)\@<! ',
                \ 'expanded': '',
                \ 'mode': 'fprz',
            \ },
        \ ]
    \ }
```

I found this here: https://github.com/kien/ctrlp.vim/issues/282

I've just added it to my vimrc, but it seems to be working well.

**Comment by hbradleyiii** [comment]
I've actually replaced the complicated regex for just a single space. It was giving me issues. I'm not sure what all it is doing, but at the moment, it seems that I always want the spaces to be ignored.

**Comment by blainesch** [comment]
This is great, I'll add it to mine as well for a few days.

**Comment by uri** [comment]
Good suggestion @hbradleyiii. I added the following to my vimrc and looks like it works fine

```
let g:ctrlp_abbrev = {
  \ 'gmode': 'i',
  \ 'abbrevs': [
    \ {
      \ 'pattern': ' ',
      \ 'expanded': '',
      \ 'mode': 'pfrz',
    \ },
    \ ]
  \ }
```
