### ISSUE TITLE
Inconsistent windows file list line endings

### ISSUE THREAD

**Issue by rene-aguirre** [ctrlpvim/ctrlp.vim#201]
CtrlP file buffer when using a custom user shell command shows an invalid CR (^M) character at end of file names.

Selecting the file for open fails with error.

The reason is pointed out in Pull Request 11, but only a single line change is required:

```
if has('patch-7.4-597') && !(has('win32') || has('win64'))
```

**Comment by mattn** [comment]
Where is pull-request 11?

**Comment by rene-aguirre** [comment]
The patch is already merged (autoload/ctrlp.vim)
