### ISSUE TITLE
submodule problems

### ISSUE THREAD

**Issue by paulosborne** [ctrlpvim/ctrlp.vim#209]
Having issues including this as a submodule, i'm getting the message

```
fatal: reference is not a tree: 564176f01d7f3f7f8ab452ff4e1f5314de7b0981
Unable to checkout '564176f01d7f3f7f8ab452ff4e1f5314de7b0981' in submodule path 'bundle/ctrlp'
```

**Comment by mattn** [comment]
It's not an issue of CtrlP. please file new issue on the plugin manager.

**Comment by paulosborne** [comment]
I'm getting that message when i run git clone --recursive when ctrlp is a submodule of my project, it's the only module that complains. The submodule is pointing to this commit: https://github.com/ctrlpvim/ctrlp.vim/tree/564176f01d7f3f7f8ab452ff4e1f5314de7b0981

It doesn't seem like an issue with the plugin manager.

**Comment by mattn** [comment]
Hmm, try to do following
```
git submodule sync
git submodule update
```

**Comment by paulosborne** [comment]
no effect, still gives the same message

```
fatal: reference is not a tree: 564176f01d7f3f7f8ab452ff4e1f5314de7b0981
Unable to checkout '564176f01d7f3f7f8ab452ff4e1f5314de7b0981' in submodule path 'bundle/ctrlp'
```

**Comment by mattn** [comment]
Please show me your .gitmodule

**Comment by paulosborne** [comment]
here it is, I appreciate you taking a look

https://github.com/paulosborne/lightweight-javascript-vimrc/blob/master/.gitmodules

**Comment by paulosborne** [comment]
This may (or may not) be relevant, when I do `git submodule status` i see the following

```
+dfd391062e6f945114bb98c06109904635f73a69 ctrlp (1.79-192-gdfd3910)
```

> Each SHA-1 will be prefixed with + if the currently checked out submodule commit does not match the SHA-1 found in the index of the containing repository.

**Comment by paulosborne** [comment]
Forking the project and using that URL for the submodule solved my problem. It's not an ideal solution but saves having to go into the submodule dir and manually checkout the latest commit.

**Comment by mattn** [comment]
hmm, at least, it's not an issue of ctrlp.
