### ISSUE TITLE
[RFC] buftype=nofile should be stored in MRU?

### ISSUE THREAD

**Issue by mattn** [ctrlpvim/ctrlp.vim#212]
I can fix this. But want to hear that someone want this behavior.

**Comment by tacahiroy** [comment]
I've never thought I want to have that.

**Comment by mattn** [comment]
>I've never thought I want to have that.

Thanks your response. Do you mean that you don't want to include nofile(s) into MRU?

**Comment by tacahiroy** [comment]
> Thanks your response. Do you mean that you don't want to include nofile(s) into MRU?
I don't mind if it includes nofile(s), I don't need to have nofiles in MRU though.

**Comment by mattn** [comment]
For example, I  use twitvim. And it use buftype=nofile for temporary window. So sad.

![](http://go-gyazo.appspot.com/192a3bbf713f18c2.png)

**Comment by tacahiroy** [comment]
that looks eyesore, so nofiles shouldn't be listed most of cases

**Comment by itchyny** [comment]
I also have trouble with this problem. I use vimfiler, calendar, agit... They create nofile buffers and all of them appears in CtrlPMRUFiles. The behaviour actually not as it used to be, and I found the commit cb5b9fffaecba684ba467d7f1d524bc05c246007 was the bad commit (`!filereadable`). I wish this issue will be solved.
