### ISSUE TITLE
Wrong order in file mode

### ISSUE THREAD

**Issue by janbaer** [ctrlpvim/ctrlp.vim#215]
CtrlP show the files in file mode not in a alphabetical order, the order is to be honest a bit confuse. Is it possible the define the order?

This are my current settings:

```
let g:ctrlp_max_height = 30
let g:ctrlp_custom_ignore = {
            \ 'dir': '\.git$\|node_modules$\|bower_components$\|bower$\|build$\|deploy$\',
            \ 'file': '\.exe$\|\.so$'
            \ }
```

**Comment by janbaer** [comment]
<img width="361" alt="screen shot 2016-03-15 at 10 19 27" src="https://cloud.githubusercontent.com/assets/528331/13773026/81bf96a0-ea97-11e5-9f64-e89465aa2e5a.png">

Maybe this screenshot explains my question a bit better. So how can I change the order of the displayed files the an alphabetical order?

**Comment by mattn** [comment]
CtrlP do sort with length of filename in default. Could you please try below?

```vim
let g:ctrlp_compare_lim = 0
```

**Comment by janbaer** [comment]
No changes the same order like before

**Comment by mattn** [comment]
Did you clean cache after the `let g:ctrlp_compare_lim = 0`?

**Comment by janbaer** [comment]
Yes, I did.

**Comment by mattn** [comment]
Then, maybe your ctrlp is old, or maybe mistaken for the setting?

See https://github.com/ctrlpvim/ctrlp.vim/issues/191#issuecomment-191321133

**Comment by janbaer** [comment]
You're right, my version of CtrlP was too old. I just updated it and now it works! Thanks!
