### ISSUE TITLE
CtrlPMRUFiles remember nofile buffer

### ISSUE THREAD

**Issue by lvht** [ctrlpvim/ctrlp.vim#216]
Some Plugins will generate buffer with the buftype set to **nofile**. This buffer should not added to the mru list. Here is an example. Both NERDTree and TagBar's temp buffer should not be remembered.

<img width="456" alt="2016-03-17 00 33 49" src="https://cloud.githubusercontent.com/assets/2030591/13820411/3a593842-ebd8-11e5-9988-a2ec6d4bbbca.png">

**Comment by mattn** [comment]
related issue https://github.com/ctrlpvim/ctrlp.vim/issues/212

**Comment by mattn** [comment]
this too https://github.com/ctrlpvim/ctrlp.vim/pull/87

@Konfekt hi, why did you remove !filereadable() in your patch? I'm thinking this patch won't be required if the !filereadable() is not removed. Did you have something issue with !fileredable()?

**Comment by Konfekt** [comment]
Yeah, I think your colleage @ludovichabant demanded it at some point, please confer the pull request. It used to be there

**Comment by lvht** [comment]
@mattn I just recover the `!filereadable()`

**Comment by mattn** [comment]
Closed by https://github.com/ctrlpvim/ctrlp.vim/pull/217
