### ISSUE TITLE
Rebuild on checkout ?

### ISSUE THREAD

**Issue by luqasz** [ctrlpvim/ctrlp.vim#221]
Hi

I was wondering if there is any way to write some script that will trigger a rebuild on `git checkout branchname` ?

**Comment by mattn** [comment]
Do you mean dynamic handling of changing of filesystem? Or something to update cache file?

**Comment by luqasz** [comment]
Yes. Dynamic handling of changing of filesystem. When I do `git checkout branchname`

**Comment by jotes** [comment]
@luqasz I guess that you could use post-checkout hook.

**Comment by mattn** [comment]
Yes, you can do it with git post-checkout with removing cache file.
