### ISSUE TITLE
<c-j> or <c-k> or <up> <down> do not navigate in results

### ISSUE THREAD

**Issue by xros** [ctrlpvim/ctrlp.vim#222]
the dotfiles in 
https://github.com/xros/dotfiles

I installed the latest ctrlp.vim
<kbd>Ctrl</kbd><kbd>p</kbd> it worked well and the ctrlp window popped out. But I can not navigate even using arrows on keyboard.

How to fix this?

**Comment by mattn** [comment]
hmm, can't reproduce it.

**Comment by xros** [comment]
key strokes of <kbd>PageUp</kbd> and <kbd>PageDown</kbd>  do not work neither.

vim: 7.4.52
OS: ubuntu 14.04 amd64
terminal: konsole 2.13.2 (from KDE)

there is no other key mappings to key <kbd>Ctrl</kbd><kbd>j</kbd>, they are only in ```ctrlp.vim```

so weird.

**Comment by xros** [comment]
@mattn what do you mean by *can't reproduce it*?

**Comment by xros** [comment]
let [s:lcmap, s:prtmaps] = ['nn <buffer> <silent>', {                                                                                                                                              
        \ 'PrtBS()':              ['<bs>', '<c-]>'],                                                                                                                                               
        \ 'PrtDelete()':          ['<del>'],                                                                                                                                                       
        \ 'PrtDeleteWord()':      ['<c-w>'],                                                                                                                                                       
        \ 'PrtClear()':           ['<c-u>'],                                                                                                                                                       
        \ 'PrtSelectMove("j")':   ['<c-j>', '<down>'],                                                                                                                                             
        \ 'PrtSelectMove("k")':   ['<c-k>', '<up>'],                                                                                                                                               
        \ 'PrtSelectMove("t")':   ['<Home>', '<kHome>'],                                                                                                                                           
        \ 'PrtSelectMove("b")':   ['<End>', '<kEnd>'],                                                                                                                                             
        \ 'PrtSelectMove("u")':   ['<PageUp>', '<kPageUp>'],                                                                                                                                       
        \ 'PrtSelectMove("d")':   ['<PageDown>', '<kPageDown>'],                                                                                                                                   
        \ 'PrtHistory(-1)':       ['<c-n>'],                                                                                                                                                       
        \ 'PrtHistory(1)':        ['<c-p>'],                                                                                                                                                       
        \ 'AcceptSelection("e")': ['<cr>', '<2-LeftMouse>'],                                                                                                                                       
        \ 'AcceptSelection("h")': ['<c-x>', '<c-cr>', '<c-s>'],                                                                                                                                    
        \ 'AcceptSelection("t")': ['<c-t>'],                                                                                                                                                       
        \ 'AcceptSelection("v")': ['<c-v>', '<RightMouse>'],                                                                                                                                       
        \ 'ToggleFocus()':        ['<s-tab>'],                                                                                                                                                     
        \ 'ToggleRegex()':        ['<c-r>'],                                                                                                                                                       
        \ 'ToggleByFname()':      ['<c-d>'],                                                                                                                                                       
        \ 'ToggleType(1)':        ['<c-f>', '<c-up>'],                                                                                                                                             
        \ 'ToggleType(-1)':       ['<c-b>', '<c-down>'],                                                                                                                                           
        \ 'PrtExpandDir()':       ['<tab>'],                                                                                                                                                       
        \ 'PrtInsert("c")':       ['<MiddleMouse>', '<insert>'],                                                                                                                                   
        \ 'PrtInsert()':          ['<c-\>'],                                                                                                                                                       
        \ 'PrtCurStart()':        ['<c-a>'],                                                                                                                                                       
        \ 'PrtCurEnd()':          ['<c-e>'],                                                                                                                                                       
        \ 'PrtCurLeft()':         ['<c-h>', '<left>', '<c-^>'],                                                                                                                                    
        \ 'PrtCurRight()':        ['<c-l>', '<right>'],                                                                                                                                            
        \ 'PrtClearCache()':      ['<F5>'],                                                                                                                                                        
        \ 'PrtDeleteEnt()':       ['<F7>'],                                                                                                                                                        
        \ 'CreateNewFile()':      ['<c-y>'],                                                                                                                                                       
        \ 'MarkToOpen()':         ['<c-z>'],                                                                                                                                                       
        \ 'OpenMulti()':          ['<c-o>'],                                                                                                                                                       
        \ 'PrtExit()':            ['<esc>', '<c-c>', '<c-g>'],                                                                                                                                     
        \ }]                                                                                                                                                                                       
                                                                                                                                                                                                   
    let g:ctrlp_map = '<c-p>'                                                                                                                                                                          
    let g:ctrlp_cmd = 'CtrlP'                                                                                                                                                                                                                                                                                                                                                                   
    set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux                                                                                                                                        
    set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows  


These are in .vimrc a minute ago I added, but it still did not work... :disappointed:

**Comment by xros** [comment]
I compiled the latest Vim 7.4.1635 https://www.snip2code.com/Snippet/160269/Build-vim-7-4-with-lua-support---Ubuntu-  

and I found that if I do ```syntax off``` in my file ```.vimrc```. the CtrlP would actually be capable of navigating.

This is so weird. I open files with syntax on by default. How can I disable it for the trade of CtrlP.

**Comment by xros** [comment]
And I read from a previous issue: https://github.com/kien/ctrlp.vim/issues/511 it stated the the issue.

he did ```syntax off``` at the beginning.

how do you use for this scenario then?

**Comment by mattn** [comment]
I tried minimal vimrc like below.
```
call plug#begin('~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()
```
But working good for me.

**Comment by xros** [comment]
@mattn this does not work for me. I installed ctrlp.vim using pathogen by ```cd ~/.vim/bundle && git clone https://github.com/ctrlpvim/ctrip.vim```

**Comment by mattn** [comment]
did you try without your customized configuration?

**Comment by xros** [comment]
@mattn Thanks! I have solved this problem. It turned out the CtrlP worked like a charm. It's just the colorshema shamed the appearance of CtrlP. https://github.com/xros/dotfiles/pull/5  After managing some colorschemas, it shows correctly.
