### ISSUE TITLE
Implement ctrlp_delete

### ISSUE THREAD

**Issue by kristijanhusak** [ctrlpvim/ctrlp.vim#225]
Hi,

Great job maintaining this plugin, it really needed it.
Beside this plugin, i also use it's "extension" https://github.com/d11wtq/ctrlp_bdelete.vim , which is really useful for me. I was wondering if it can be added to the core here? I believe many people will use it, and it's not really big  (~70 lines of code). If it's ok, i'll create a PR. 

Thanks.

**Comment by tacahiroy** [comment]
it's worth to add this feature as a default extension, IMHO.
any input?

**Comment by ludovicchabant** [comment]
I didn't know about this plugin, it's pretty cool! Since @d11wtq wrote it he may have some insight, but otherwise go for it, thanks!

**Comment by d11wtq** [comment]
It's already implemented if you're on the latest master. Open `:CtrlPBuffer`, mark any buffers you want to delete, then use `F7` to delete them.

**Comment by d11wtq** [comment]
Commit that added it: https://github.com/ctrlpvim/ctrlp.vim/commit/dba9de71a07e9d0357157cc89281af8e53f6599c#diff-c9de02bff2ec6d5e66b2f5f71beb595dR892

**Comment by kristijanhusak** [comment]
@d11wtq can it be remapped to something else?

**Comment by kristijanhusak** [comment]
Found it in docs. Thanks.
