### ISSUE TITLE
CtrlP doesn't search in submodule.

### ISSUE THREAD

**Issue by alexche8** [ctrlpvim/ctrlp.vim#227]
I have project with .git root in "project" folder. Submodule located 3 levels deeper - "project/Source/AppEngine/submodule" . CtrlP doesn't search files in "submodule" folder. What do I need to setup to make it possible? Thanks.

**Comment by ludovicchabant** [comment]
It should do it already -- that works fine here for me. What is your current working directory or buffer when you invoke CtrlP? Is it somewhere inside `project`, or inside one of the submodules?

**Comment by alexche8** [comment]
It is inside project. I opened "project/Source/AppEngine/submodule/views/api/tracking.py" previously. I have "project/Source/AppEngine/main.py" opened now. So I have open ctrlP, started to type 'tracking.py'. but no results.

**Comment by alexche8** [comment]
Any ideas?

**Comment by alexche8** [comment]
Anyway, I added 
let g:ctrlp_cmd = 'CtrlPMixed' to vimrc. So it search in buffers also. This is enough for me for now.
