### ISSUE TITLE
wrong slashed used on Linux starting with commit a645dd9

### ISSUE THREAD

**Issue by zandrmartin** [ctrlpvim/ctrlp.vim#230]
Starting with commit a645dd9, when opening a file, the path is prefixed with a backslash on Linux.

To reproduce: if pwd is `~/.config/nvim/plugged/ctrlp.vim`, attempt to open `autoload/ctrlp/dir.vim` with CtrlP:
- commit f327ea5: opens `~/.config/nvim/plugged/ctrlp.vim/autoload/ctrlp/dir.vim` successfully
- commit a645dd9: attemps to open `~/.config/nvim/plugged/ctrlp.vim\autoload/ctrlp/dir.vim`

As of right now all the commits from a645dd9 onward have this problem.

**Comment by mattn** [comment]
following patch fix this issue?
```diff
diff --git a/autoload/ctrlp.vim b/autoload/ctrlp.vim
index 8e99843..062b732 100644
--- a/autoload/ctrlp.vim
+++ b/autoload/ctrlp.vim
@@ -1941,7 +1941,11 @@ fu! s:bufnrfilpath(line)
 	if s:isabs(a:line)
 		let filpath = fnamemodify(a:line, ':p')
 	el
-		let filpath = fnamemodify(s:dyncwd.(&shellslash ? '/' : '\').a:line, ':p')
+		if (has('win32') || has('win64')) && !&shellslash
+			let filpath = fnamemodify(s:dyncwd.'\'.a:line, ':p')
+		el
+			let filpath = fnamemodify(s:dyncwd.'/'.a:line, ':p')
+		en
 	en
 	let bufnr = bufnr('^'.filpath.'$')
 	if (a:line =~ '[\/]\?\[\d\+\*No Name\]$' && !filereadable(filpath) && bufnr < 1)
```

**Comment by zandrmartin** [comment]
Yes, that seems to work fine. Thanks!

**Comment by mattn** [comment]
Thanks!

**Comment by kminh** [comment]
A possibly related issue: when using ctrlp.vim on Windows without shellslash (`set noshellslash` is in my vimrc), ctrlp shows matched files in their full paths instead of relative paths, for example I'm seeing this:
```
C:\Codes\x\y\z\file1.cs
C:\Codes\x\y\z\t\file2.cs
```
instead of this:
```
x\y\z\file1.cs
x\y\z\t\file2.cs
```

**Comment by mattn** [comment]
I also use noshellslash, and doesn't set g:ctrlp_user_command. But I get relative paths.

**Comment by mattn** [comment]
What do you have another configuration about CtrlP?

**Comment by kminh** [comment]
I do set `g:ctrlp_user_command`, as shown below:

```vim
  let g:ctrlp_user_command = 'ag %s -l -U --hidden
    \ --ignore .git
    \ --ignore dist
    \ --ignore node_modules
    \ --ignore bower_components
    \ --ignore git_components
    \ --ignore cache
    \ --ignore log
    \ --ignore images
    \ --nocolor -g ""'
```
Removing it seems to produce relative paths.

My ag binary is provided by msys2: https://sourceforge.net/projects/msys2/files/Base/x86_64/

Any ideas?

**Comment by mattn** [comment]
If the command that is specified by ctrlp_user_command output absolute paths, list on CtrlP should be absolute paths. This behavior didn't change even though before https://github.com/ctrlpvim/ctrlp.vim/commit/a645dd94ddd1b5d9a2eacefc622a631ddd5174c7 AFAIK.

**Comment by kminh** [comment]
The output of `ag` on both my Windows and Linux boxes contain absolute paths but on Linux the output of CtrlP contain relative paths instead.

**Comment by mattn** [comment]
Ah, maybe I figured-out. CtrlP remove base dir from the list of paths after calling user's command. But the base dir is backslash separated on windows. But maybe your list from ag is slash separated.

**Comment by mattn** [comment]
Maybe fixed in https://github.com/ctrlpvim/ctrlp.vim/commit/3f1e62e4d930bc4148c93199fa50f74132cbc354
