### ISSUE TITLE
cannot open files in MRU

### ISSUE THREAD

**Issue by Konfekt** [ctrlpvim/ctrlp.vim#233]
Since fb87877da84b335060bee08a74fd026b92fd5db2 files in :CtrlpPMRU can no longer be opened.

To reproduce, 
```vim
let g:ctrlp_cache_dir = '~/.config/ctrlp'
```
and add in `~/.cache/ctrlp/mru/cache` the single line 
```
~/.cache/ctrlp/mru/cache
```
type `:CtrlPMRU` and hit Enter.

Expected:

```
~/.cache/ctrlp/mru/cache
```
is openend.

What happends:

`expand(getcwd()) . '~/.cache/ctrlp/mru/cache'` =  `~/~/.cache/ctrlp/mru/cache`  is openend.

Notice that  
```
let g:ctrlp_tilde_homedir = 1
```
no files in ~ can be opened any longer.

**Comment by mattn** [comment]
Below's patch will fix this?
```diff
diff --git a/autoload/ctrlp.vim b/autoload/ctrlp.vim
index d80cbcd..222c37c 100644
--- a/autoload/ctrlp.vim
+++ b/autoload/ctrlp.vim
@@ -1933,7 +1933,7 @@ fu! s:isabs(path)
 endf
 
 fu! s:bufnrfilpath(line)
-	if s:isabs(a:line)
+	if s:isabs(a:line) || a:line =~ '^\~[/\\]'
 		let filpath = a:line
 	el
 		if (has('win32') || has('win64')) && !&shellslash
```

**Comment by Konfekt** [comment]
Fantastic, works!
