### ISSUE TITLE
weird characters in ctrlp search window

### ISSUE THREAD

**Issue by shangsunset** [ctrlpvim/ctrlp.vim#236]
when using ctrlp in neovim, there are always weird character on the last line
![screen shot 2016-02-03 at 7 22 47 pm](https://cloud.githubusercontent.com/assets/3700269/12804071/a2ff0688-cabd-11e5-8167-9ee6dda7f6fa.png)

Tested in bash, zsh, fish. same result.

**Comment by mattn** [comment]
Maybe it's a bug of neovim that can't handle escape sequence correctly.
