### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by gerases** [ctrlpvim/ctrlp.vim#237]
Hi,

I have this in my config:

```
let g:ctrlp_switch_buffer = 'E'
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }
```

That allows me to press `Enter` on a selected file and open it in a new tab. But the problem is that when they are no tabs yet, it will not use the current empty window to open the file but instead will open a new tab. After that I have to close the empty window left behind.

How do I configure it in such a way that it reuses the empty window first and then opens new tabs after that?

Thanks!

**Comment by gerases** [comment]
```
    " Close an extra tab that CtrlP opens
    function! Close_empty_tab()
     " If the buffer does not have a file loaded
     if (len(expand('%:t')) == 0)
       :quit
     end
    endfunction
```

You can have a keybinding to call that function. I went out on a limb and created an auto command like so:

`:autocmd TabEnter * :call Close_empty_tab()`

If you see a problem with my solution, let me know. Otherwise, please use at your own risk.

**Comment by mattn** [comment]
I don't think this is not a feature that CtrlP must have.

**Comment by gerases** [comment]
​Just to make sure i understand the double negatives correctly. you meant
CtrlP *should *have that feature?​

**Comment by mattn** [comment]
Ah, sorry. I mean:

> I think this is NOT a feature that CtrlP must have.

**Comment by gerases** [comment]
Ok, I did implement it with Autocommands and it seems to be working.
