### ISSUE TITLE
Remap F5 reloading

### ISSUE THREAD

**Issue by PureW** [ctrlpvim/ctrlp.vim#238]
How would one go about remapping F5 to something else? F5 is already used in my terminal multiplexer.

I don't see a vim-macro to map in the documentation:
```
Function keys:
    
  <F5>
    - Refresh the match window and purge the cache for the current directory.
    - Remove deleted files from the MRU list.
```

**Comment by mattn** [comment]
put this into your vimrc
```vim
let g:ctrlp_prompt_mappings = {
\ 'PrtClearCache()': ['<F6>'],
\}
```

**Comment by PureW** [comment]
Thanks! Is this information in the documentation?

**Comment by mattn** [comment]
Maybe you can find assign of key-mappings on `:help ctrlp_prompt_mappings`. ;)

**Comment by PureW** [comment]
Ohh ok. Is prompt_mappings common terminology in the vim-sphere? I had no idea I was supposed to look for that.
