### ISSUE TITLE
ctrlp doesn't find file

### ISSUE THREAD

**Issue by robertbnd** [ctrlpvim/ctrlp.vim#239]
Hi I have this in .vimrc
let g:ctrlp_max_files=0
let g:ctrlp_max_depth = 40
let g:ctrlp_extensions = ['buffertag', 'tag', 'line', 'dir', 'tmux', 'mpc'] "

but I can't find my file 
/home/USER/workspace/bakery/vendor/psy/psysh/src/Psy/CodeCleaner/MagicConstantsPass.php

![screenshot from 2016-04-19 11-38-57](https://cloud.githubusercontent.com/assets/4907027/14647510/c5ef2afa-0623-11e6-9b28-3f6ab3cd8298.png)

**Comment by mattn** [comment]
> /home/USER/workspace/bakery/vendor/psy/psysh/src/Psy/CodeCleaner/MagicConstantsPass.php

Where is the base directory? `/home/USER/workspace/bakery` ?

**Comment by mattn** [comment]
Seems working good to me.

![](https://i.gyazo.com/a5e42a2dc479bf6c70667b19087d0ff8.png)

**Comment by robertbnd** [comment]
yes ...
![screenshot from 2016-04-19 11-47-24](https://cloud.githubusercontent.com/assets/4907027/14647791/f054fa12-0624-11e6-808a-80cfd999ddc0.png)

mmm then the only difference that I can find I am using neovim

**Comment by robertbnd** [comment]
regexp mode I can find the file
![screenshot from 2016-04-19 12-32-52](https://cloud.githubusercontent.com/assets/4907027/14649054/0134d50e-062b-11e6-960e-8d588bae1e76.png)

**Comment by robertbnd** [comment]
oh!!  I am so sorry I am fool  
I must write more letters of the name. 
on other hand I see many posts from you
just say Thanks you are awesome :D
