### ISSUE TITLE
ctrlp_by_filename

### ISSUE THREAD

**Issue by skgbanga** [ctrlpvim/ctrlp.vim#243]
Has this option been deprecated? I tried setting it, but to no effect.

**Comment by skgbanga** [comment]
It looks like I have significantly less customisable options than are mentioned in ctrlp doc:
<img width="1433" alt="vim_ctrlp" src="https://cloud.githubusercontent.com/assets/8398696/14803928/5aa84d5e-0b2c-11e6-90df-f9d388af0f79.png">

**Comment by mattn** [comment]
Not deprecated. https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L59
What value did you set?

**Comment by skgbanga** [comment]
Actually I saw the value in the code yesterday, but for some reason, I am only shown a subset of values only (look at the screenshot above)

**Comment by mattn** [comment]
You should look `>d>` on the prompt when setting `let g:ctrlp_by_filename = 1`

**Comment by skgbanga** [comment]
Hmph. This is something new for me. (I verify that I can set this global flag and then do filename search)

I was of the opinion that vim can display all the possible global variables that I can set when I do
:let g:ctrlp<C-d> inside vim

Maybe, I need to understand what global values are shown and what are not shown inside vim. 

Thanks for your help though!

**Comment by mattn** [comment]
several options are checked at runtime.

**Comment by skgbanga** [comment]
Ok, thanks!
