### ISSUE TITLE
How to use CtrlP in Buffer + File mode only, without MRU?

### ISSUE THREAD

**Issue by Coaxial** [ctrlpvim/ctrlp.vim#246]
I work on several different projects between work and home. The MRU option messes with the result list, matching files from other, unrelated projects.

From reading the help, it seems the only available modes are:
1. File
2. Buffer
3. File, Buffer, MRU

Is there an option to only search files and buffers, without MRU?

Thanks,

**Comment by mattn** [comment]
Try https://github.com/ctrlpvim/ctrlp.vim/pull/220

**Comment by mattn** [comment]
closed by #220
