### ISSUE TITLE
Adding support for Go and gotags?

### ISSUE THREAD

**Issue by hdra** [ctrlpvim/ctrlp.vim#250]
Would you consider adding support for the Go programming language? Ctags is able to work with Go files with some config tweak, but [gotags](https://github.com/jstemmer/gotags) project is able to generate ctags compatible tags, and it also works better with Go semantics.

I realize that this does requires the installation of an external program, but I noticed there is a similar support for jsjtags, so maybe thats not an issue?

**Comment by QMonkey** [comment]
+1

**Comment by mattn** [comment]
Closed by #270
