### ISSUE TITLE
Running python process after Vim closing

### ISSUE THREAD

**Issue by maliavko** [ctrlpvim/ctrlp.vim#252]
Hi all.
There is little issue I noticed in Vim last night. When I open py-file by Vim there is python process will be spawned together with Vim. Then if I use files search by CtrlP plugin in my huge python project and select another py-file there is new python process will be spawned too. So when then I close Vim by ":q" command one of these processes is still running.

Environment:
Win7 x64
Vim 7.4 with Py2 support

I can attach little video or provide some more information if needed. Thank you.

**Comment by mattn** [comment]
What plugins do you use?

**Comment by maliavko** [comment]
My full Vundle plugins list from _vimrc:
- Plugin 'VundleVim/Vundle.vim'
- Plugin 'tpope/vim-fugitive' 
- Plugin 'vim-scripts/indentpython.vim'
- Plugin 'andviro/flake8-vim'
- Plugin 'jnurmine/Zenburn'
- Plugin 'altercation/vim-colors-solarized'
- Plugin 'scrooloose/nerdtree'
- Plugin 'kien/ctrlp.vim'
- Plugin 'git://repo.or.cz/vcscommand'
- Plugin 'scrooloose/nerdcommenter'
- Plugin 'will133/vim-dirdiff'
- Plugin 'vim-scripts/taglist.vim'
- Plugin 'bitc/vim-bad-whitespace'
- Plugin 'lyokha/vim-xkbswitch'
- Plugin 'Raimondi/delimitMate'
- Plugin 'vim-airline/vim-airline'
- Plugin 'bling/vim-bufferline'
- Plugin 'vim-airline/vim-airline-themes'
- Plugin 'Valloric/YouCompleteMe'
- Plugin 'rking/ag.vim'
- Plugin 'alfredodeza/pytest.vim'
- Plugin 'SirVer/ultisnips'
- Plugin 'honza/vim-snippets'

Python compiled with Py2 (no Py3) sopport.

**Comment by maliavko** [comment]
Some update: the bug appears only when I open Vim using only console command 'vim' in anywhere in my filesystem. In that case python process will be spawned directly behind the main process:
![image](https://cloud.githubusercontent.com/assets/18325988/15350709/732739ee-1ce3-11e6-9767-cbb466d62a85.png).
If then I use CtrlP and open any *.py file another python process will be spawned as well:
![image](https://cloud.githubusercontent.com/assets/18325988/15350756/b48ac2c0-1ce3-11e6-80d9-c4dc4c6952f6.png)

And the most interesting: if I remove YouCompleteMe plugin, there are no python processes at all (even if I follow steps described above). I think I should post this issue to the YCM plugin thread.Thanks a lot, guys.

**Comment by mattn** [comment]
Okay. Thanks your explaining.
