### ISSUE TITLE
Close multiple marked buffers

### ISSUE THREAD

**Issue by kaatish** [ctrlpvim/ctrlp.vim#254]
> Use <c-z> to mark/unmark multiple files and <c-o> to open them.

Is there anyway to close multiple buffers after marking them with <c-z>? I tried :bd but that didn't work.

Thanks.

**Comment by tacahiroy** [comment]
Try `<F7>` to delete buffers

**Comment by kaatish** [comment]
That actually works. Thanks! Is there any way I can remap it from `<F7>` to something else?

**Comment by kaatish** [comment]
Hey. I found it in the docs. Closing this issue.
