### ISSUE TITLE
A questurn about ctrlp.

### ISSUE THREAD

**Issue by wsdjeg** [ctrlpvim/ctrlp.vim#257]
I want to use ag as ctrlp's file search tools, so I use option 
```vim
g:ctrlp_user_command = 'ag %s -i --hidden -g ""'
```
By default, ag will auto ignore patterns in `~/.gitignore` and `./.gitignore`. but I have some local test scripts in `./localtest/` whitch has been added into `./.gitignore`. how could I show these files in ctrlp buffer.

BTW, I have the way bellow, all of them do not work.

add `-a` option to ag cmd, it will list all files , but I want ignore patterns in gitignore and patterns following  `--ignore`.

**Comment by tacahiroy** [comment]
Have you tried `-U` option for `ag`?
```
-U --skip-vcs-ignores
    Ignore VCS ignore files (.gitignore, .hgignore, svn:ignore), but still use .agignore.
```

**Comment by wsdjeg** [comment]
thanks, but I mean I need the patterns in gitignore. and I want incloud the directory I want

**Comment by tacahiroy** [comment]
That's the ag side of thing rather than ctrlp side of problem, right?
-- 

Takahiro Yoshihara
tacahiroy@gmail

**Comment by wsdjeg** [comment]
yeah, I got it. so the issue can be closed.
