### ISSUE TITLE
Latest CtrlP doesn't work with latest neovim

### ISSUE THREAD

**Issue by osa1** [ctrlpvim/ctrlp.vim#262]
I'm getting errors like:

```
Error detected while processing function ctrlp#init[17]..<SNR>77_BuildPrompt:
line    5:
E171: Missing :endif
```

Then this:

```
TypeError: decode() argument 1 must be str, not bytes
```

Then lots of other errors follow.

**Comment by mattn** [comment]
Sorry, code of ctrlp.vim doesn't have `decode` keyword. Maybe something wrong on only your's. And maybe `TypeError` is keyword of python. Are you using ctrlp's extension which use python?

**Comment by mattn** [comment]
gg

**Comment by osa1** [comment]
Hmm, I'm using this https://github.com/FelikZ/ctrlp-py-matcher I guess that's the problem then. Thanks.
