### ISSUE TITLE
CtrlPBuf Bug

### ISSUE THREAD

**Issue by amadeus** [ctrlpvim/ctrlp.vim#263]
When you attempt to use it from a netrw buffer, it just doesn't work, and I get a bizarre error, see this screenshot:

![netrw example](https://dl.dropboxusercontent.com/s/e53n58eny08dflz/No_Name_2016-06-13_10-59-49.png?dl=0)

**Comment by mattn** [comment]
Try to do `:ball`? Do you see the buffer `Netrw History#` as splited?

**Comment by amadeus** [comment]
When I do `:ball` I get a horizontal split, that initially looks like:

![example1](https://dl.dropboxusercontent.com/s/6pz38dhr42da6yp/No_Name_2016-06-14_21-51-54.png?dl=0)

And if I used `ctrl + w j` to move down to that bottom split, I get

![example2](https://dl.dropboxusercontent.com/s/8nxgb4rzndh0jyz/No_Name_2016-06-14_21-52-20.png?dl=0)

**Comment by mattn** [comment]
could you please show me how to reproduce? and small configurations enough to reproduce.

**Comment by amadeus** [comment]
Woah, digging around, there's something really weird going on here, perhaps it has some bizarre bug with the hotkey I have setup for it.

The configuration I have is:

```
nnoremap <leader>b :CtrlPBuffer<cr>
```

To reproduce, I simply open vim, and then performed `:edit ~/` to bring up a netrw buffer. Then I pressed `<leader>b` to trigger CtrlPBuffer and I get the error.

**Comment by mattn** [comment]
Hmm, I can't reproduce.

**Comment by amadeus** [comment]
Strange, ok. I'll look into it more some time and see if I can find a better way to reproduce.

**Comment by mattn** [comment]
No need to close if you are still getting problem.

**Comment by amadeus** [comment]
It's probably something related to another plugin or setup that I have, so no worries.
