### ISSUE TITLE
Possible to jump to current file.

### ISSUE THREAD

**Issue by mporras** [ctrlpvim/ctrlp.vim#264]
I sometimes invoke CtrlP and start typing a filename only to be surprised that it doesn't appear in the list. Then I realize CtrlP doesn't show the file because it's already in the current buffer.

I'd like the option to include the current file in the list, so I don't have to first check whether that file happens to be open in the current buffer already. (That takes deciseconds! Typing is faster than looking.)

Taken from: https://github.com/kien/ctrlp.vim/issues/580

**Comment by mattn** [comment]
Did you see this issue? https://github.com/ctrlpvim/ctrlp.vim/issues/95 cc: @ludovicchabant

**Comment by mporras** [comment]
Closed as duplicate of https://github.com/ctrlpvim/ctrlp.vim/issues/95
