### ISSUE TITLE
CtrlP cant find some file

### ISSUE THREAD

**Issue by mingchaoyan** [ctrlpvim/ctrlp.vim#265]
OSX 10.11.5

Vim 7.4

Hi

I try to use ctrlp to find App.cs in my project, but I can't find it using CtrlP.

<img width="1280" alt="od0wo" src="https://cloud.githubusercontent.com/assets/2843100/16030554/bf441b20-3224-11e6-89d5-8fc2b0fee648.png">

My only vim config about ctrlp is

> let g:ctrlp_max_files = 0
> let g:ctrlp_max_depth = 40
> let g:ctrlp_follow_symlinks=1

and

> :set path?   
> 
> path=.,/usr/include,,,**

 If i move Assets/Scripts/Zi/Componets/App.cs to Assets/Scripts/App.cs CtriP can find it

So, is it a bug, or I have to make some config.

Thanks

**Comment by mattn** [comment]
try this.

```
let g:ctrlp_path_nolim = 1
```
could you please try to scroll-up to find app.cs?

**Comment by mattn** [comment]
I don't mean 'this is not a problem'. I just want to figure out what is the problem.

**Comment by mingchaoyan** [comment]
> try this.
> 
> let g:ctrlp_path_nolim = 1

@mattn  it does not work

How to scroll-up in the result of ctrlp?  I try <c-j> and <c-k>, but it stop at top and bottom

**Comment by mattn** [comment]
do you use latest ctrlp.vim?

**Comment by mingchaoyan** [comment]
Yes

tig show the last commit is your

> 2016-06-08 11:41 mattn                 M─┐ [master] {origin/master} {origin/HEAD} Merge pull request #259 from ctrlpvim/fix-253

**Comment by mattn** [comment]
do you set `g:ctrlp_user_command` to something?

**Comment by mingchaoyan** [comment]
no

All my vimconfig is here 
https://github.com/mingchaoyan/dotvim

**Comment by mattn** [comment]
Ah, because you already open App.cs.

**Comment by mingchaoyan** [comment]
no

I open vim on the root of the project, then ctrlp  input app.cs  and can not find it.
I post the pic only because I want show helper my file tree

**Comment by mattn** [comment]
okay, then please try following

1. put `let g:ctrlp_path_nolim = 1` into your vimrc
2. change directory to root of your repository
3. type CTRL-P
4. browse `<c-j>` or `<c-k>` with scrolling whether the file exists.

**Comment by mingchaoyan** [comment]
It seems I have 18810 files to scroll

could you give me another method to check whether the file exists(maybe print the result to a log file)

**Comment by mattn** [comment]
type three letter `app` and try to browse?

**Comment by mingchaoyan** [comment]
it only show 

> Library/ScriptMapper
> Library/InspectorExpandedItems.asset
> Library/BuildPlayer.prefs
> Assets/TriggerEventProExampleFiles.meta
> Assets/spine-csharp.meta
> Assets/PoolManagerExampleFiles.meta
> Assets/AppRes.meta
> Assembly-CSharp.csproj
> Assembly-CSharp-firstpass.csproj
> Assembly-CSharp-Editor.csproj

and I use \<c-j\> and\<c-k\>  just make the bell ring and no scroll

**Comment by mattn** [comment]
possibly, it is cache. try to `:CtrlPClearCache` and go CtrlP.

**Comment by mingchaoyan** [comment]
no 
it does not work


I am trying to upload some file to my github  so you can clone the repo and debug it

**Comment by mingchaoyan** [comment]
@mattn 

try

git clone git@github.com:mingchaoyan/test.git

it may Reappear the bug

**Comment by mattn** [comment]
Okay, I reproduced it. I'll look into it in later. Thanks.

**Comment by mingchaoyan** [comment]
@mattn have you find the bug?

**Comment by mingchaoyan** [comment]
@mattn have you find the bug?

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/3c53e358cd380273.png)

I can find the file with absolute path specified. so maybe, filter is wrong.

**Comment by mattn** [comment]
could you please try https://github.com/ctrlpvim/ctrlp.vim/pull/266 ?

**Comment by mattn** [comment]
Note that you will get better to match with `App.cs` not `app.cs`.

**Comment by mingchaoyan** [comment]
#266  can use App.cs  to find the file (but app.cs cant)

**Comment by mattn** [comment]
What way to reproduce? Should move App.cs into somewhere?

**Comment by mingchaoyan** [comment]
Sorry, I can't upload the whole project because of the business cause and I try to reproduce it without using the whole project, but I faild. Actually another pulgin(lookupfile https://github.com/vim-scripts/lookupfile) can find the file. So I may move to this plugin, instead of spending too much time in this.   **Really very thanks for your help @mattn !!!**

**Comment by mattn** [comment]
You don't need upload actual files. If possible, please send me the list of files.

```
$ find . > list.txt
```

**Comment by mingchaoyan** [comment]
ok

**Comment by kormat** [comment]
#266 broke the fuzzy filter for me. Before i could type some letters from the dir and some from the filename, and it would find the file. Now it finds nothing, unless i type only letters from one or the other.

**Comment by kormat** [comment]
(I can't find any standard instructions on how to give reproducible instructions)

**Comment by mattn** [comment]
could you please show me how to reproduce?

**Comment by kormat** [comment]
Ok, here's an example dir structure:
```
.
./knee
./knee/leg
./foot
./head
./hand
```

And here's my entire .vimrc for this:
```
$ cat ~/.vimrc
set runtimepath^=~/.vim/bundle/ctrlp.vim
```

If i open vim, hit ctrl-p, and type `kn`, or `le` it works fine. But if i try `kl`, i get `== NO ENTRIES ==`. Until #266 was merged, this worked fine.

I'm using vim 7.4.52, from ubuntu 14.04.

**Comment by pabuisson** [comment]
Same issue as @kormat for me, it looks like #266 broke this for me as well. I just went and reverted the `autoload/ctrlp.vim` file to what it was before, and it's working again.

I'm using NVIM 0.1.4 on Mac OS 10.11.5. It stopped working since this commit.

**Comment by mattn** [comment]
Yes, I changed behavior. When many files exists, and you want to find a file in deep directory structure, CtrlP can't list up them. Hmm, okay, I change this behavior to work only with set new option.

**Comment by mattn** [comment]
Now default is original match behaivor.

**Comment by kormat** [comment]
@mattn - wonderful, thank you!
