### ISSUE TITLE
Clarification with CtrlPLine

### ISSUE THREAD

**Issue by idd79** [ctrlpvim/ctrlp.vim#268]
Hi, thanks for a great plugin.

I am trying to use the command :CtrlPLine and according to the documentation, if no [buffer] is specified it should search in all listed buffers, however it is only searching in the current buffer, despite having other buffers open as well. Am I missing something about this command or is this feature just not included? Thanks!

**Comment by mattn** [comment]
Hmm, can't reproduce this.

```
$ cd ~/dev/vim
$ vim src/mbyte.c src/window.c
:ball
:new
:only
:CtrlPLine
```

![](http://go-gyazo.appspot.com/3d160da0e17f591b.png)

**Comment by idd79** [comment]
Thanks for replying and for somehow clarifying. Actually I just tried it further and it does work, but some how lets say I open two Ruby files and search for lines that start with "def", sometimes it will only show me results from the same buffer, but if I add more characters to the search, say "def sav", it does show results from other buffers as well. And I think it is just because the search gives you 10 results, so sometimes results from other buffers might not appear at first. 

Sorry I overlooked that. Thanks again! I am closing this then.

**Comment by dragonxlwang** [comment]
I am having the same issue that using `CtrlPLine` only searches current buffer instead of all opened buffers.

Here's a minimal vimrc that I used to reproduce:
https://gist.github.com/dragonxlwang/bd51097cd48ffd06744146b65ed3a8ce

And I was using the latest version of ctrlp

**Comment by mattn** [comment]
No configuration for ctrlp?

**Comment by dragonxlwang** [comment]
In the MWE, I didn't set any config for ctrlp. I used `:CtrlPLine` to call the function. I tested it on a centos 7. It neither works on my MBP.

**Comment by mattn** [comment]
The files are existing at each different directories?

**Comment by dragonxlwang** [comment]
for my test, I have two files `~/.vimrc` and `~/.zshrc`, so they are in the same directory `~`

**Comment by mattn** [comment]
Could you please what operation did you do?

1. open vim with two arguments.
2. `:CtrlPLine`

right?

**Comment by dragonxlwang** [comment]
yes. 

Sorry that I didn't give the details:

```
$ cd ~
$ vim .vimrc .zshrc
:ball
:new
:only
:CtrlPLine
```
