### ISSUE TITLE
CtrlPBufferFiles

### ISSUE THREAD

**Issue by sassanh** [ctrlpvim/ctrlp.vim#271]
It'd be great if we had an `CtrlPBufferFiles` that initially shows what `CtrlPBuffer` shows then as user types, it searches files like in `CtrlP` itself. When user presses `<c-u>` or removes its input it should show what `CtrlPBuffer` shows again.

**Comment by sassanh** [comment]
No, I think it's better to have a new mode (not toggling on old modes) that when user input is empty shows results of `CtrlPBuffer` (last opened buffers), and when user starts typing shows results of normal `CtrlP`.

**Comment by mattn** [comment]
Ah, you want to do two action in the one session of CtrlP.

1. select buffers on CtrlP if doesn't have input.
2. select files if have some inputs.

So, on 1, it should use `<c-j>` or `<c-n>` only. if you have many buffers, you should be difficult to choice the buffer you want.

**Comment by sassanh** [comment]
Yes I want exactly what you described. In my environment buffers is a subset of files. I use buffers list only to see my last visited files, I don't need more than last 10 buffers (even if 1000 buffers are open) but when I type something in CtrlP window I want it to find it among all files in project (files not buffers). That's my usecase. Do you think it's possible to have this?

**Comment by sassanh** [comment]
I was able to implement it by adding these lines:

    if exists('g:ctrlp_input_callback')
      execute call(g:ctrlp_input_callback, [str, s:itemtype])
    endif

in file `autoload/ctrlp.vim` in function `s:Update`. It lets me to set a callback for user input. Then by adding these lines to my vimrc I got what I wanted:

    func! CtrlPCallback(input, itemtype)
        if a:itemtype != 1
            return
        endif
        if len(a:input)
            let g:ctrlp_lines = ctrlp#files()
        else
            let g:ctrlp_lines = ctrlp#buffers()
        endif
    endfunc
    let g:ctrlp_input_callback='CtrlPCallback'

As you see it's a dirty hack. It'd be great if we could manage to have a good api solution for this kind of use cases.
