### ISSUE TITLE
Shortcut to yank string from ctrlp menu

### ISSUE THREAD

**Issue by rcorre** [ctrlpvim/ctrlp.vim#272]
Sometimes I just want to grab a file path and put it on the clipboard, and ctrlp is the easiest way to find that file.
It would be nice to have a shortcut in ctrlp (`<c-y>` maybe?) to yank the selected text.

**Comment by rcorre** [comment]
Sorry, don't know why I said clipboard. I just meant a normal yank (though maybe clipboard copy would be useful as well).

**Comment by tacahiroy** [comment]
The default key mapping to start visual mode is overwritten by ctrlp.
So selecting using mouse (left button), then press `y` should work for you.

**Comment by rcorre** [comment]
This being vim, I'd rather avoid using the mouse :)

**Comment by mattn** [comment]
`<c-y>` is already assigned as create directory.

**Comment by mattn** [comment]
See https://github.com/ctrlpvim/ctrlp.vim/pull/273

**Comment by mattn** [comment]
Closed by https://github.com/ctrlpvim/ctrlp.vim/pull/273
