### ISSUE TITLE
Lately ctrlp started indexing very slowly on every search

### ISSUE THREAD

**Issue by kovpack** [ctrlpvim/ctrlp.vim#277]
Lately `ctrlp` started doing index a few seconds on every search, however, not long ago it was extremely fast, so that I even did not notice indexing at all. The strange thing is, that indexing time does not depend on the directory size: it does `Indexing...` the same amount of time in the directory with 10 files, and in the directory with 10000 files. What can cause that?

**Comment by mattn** [comment]
Do you use ctrl_user_command?

**Comment by kovpack** [comment]
I have such stuff in my config
```
if exists("g:ctrlp_user_command")
  unlet g:ctrlp_user_command
endif
if executable('ag')
  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command =
    \ 'ag %s --files-with-matches -g "" --ignore "\.git$\|\.hg$\|\.svn$"'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
else
  " Fall back to using git ls-files if Ag is not available
  let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . --cached --exclude-standard --others']
endif
```

**Comment by mattn** [comment]
Which do you mean the delay befoer display `Index...` or waiting while displaying `Indexing...`?

**Comment by kovpack** [comment]
`Indexing...`. It was much much faster some time ago.

**Comment by mattn** [comment]
So I guess that it takes the much time to find the files with ctrlp_user_command. Did you try the command as same as CtrlP did on your terminal?

**Comment by kovpack** [comment]
Yes, I tried, and it was really fast. Lightning fast, basically.

**Comment by mattn** [comment]
`system()` function of vim use shell. So if you have heavy configuration in your .bashrc or .zshrc, it take much time to start ag or find.

**Comment by kovpack** [comment]
Yeap, that was really in my `zsh` startup files. Removed `nvm` stuff - and now search is super fast :)
