### ISSUE TITLE
Accept/cancel input programmatically in extensions

### ISSUE THREAD

**Issue by bkudria** [ctrlpvim/ctrlp.vim#28]
_(This is a duplicate of kien/ctrlp.vim#524)_

https://github.com/phalkunz/ctrlp-related is a very useful plugin that lists related files relative to the current file. However, often times there are no related files, or only one - in that case, it would be useful to cancel ctrlp or accept the one result respectively, programmatically from the extension.

Currently, there isn't a good way to do that. I've succeed in almost possibly getting this working using `feedkeys`, but it requires managing the global `g:ctrlp_buffer_func` in an incredibly error-prone way.

An official supported option to enable this behavior would be very welcome.

**Comment by ggVGc** [comment]
I just made a PR adding an option exactly for this(although I use it for ctrlp-funky), #80

**Comment by bkudria** [comment]
Closed by https://github.com/ctrlpvim/ctrlp.vim/pull/80
