### ISSUE TITLE
CtrlPMixed, CtrlPDir, CtrlPLine, CtrlPBufTag, CtrlPTag and CtrlPQuickFix commands are no longer working after commit for #280

### ISSUE THREAD

**Issue by phongnh** [ctrlpvim/ctrlp.vim#281]
Like the title says it all. It also affects other CtrlP plugins.

![screen shot 2016-07-29 at 10 40 46 am](https://cloud.githubusercontent.com/assets/438791/17237146/f0890070-5578-11e6-8fa5-24b53f49a5be.png)

**Comment by mattn** [comment]
should be already fixed in https://github.com/ctrlpvim/ctrlp.vim/commit/36f34cdfec50d89e0cd70604a3b4130254bc6612

**Comment by phongnh** [comment]
Thanks @mattn. The problem was fixed. Close it now.
