### ISSUE TITLE
Files open in NERDTree's pane if updatetime is low

### ISSUE THREAD

**Issue by sprt** [ctrlpvim/ctrlp.vim#286]
.vimrc:

```
execute pathogen#infect()
call pathogen#helptags()

" Open NERDTree on startup
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

set updatetime=1000
```

Repro:

1. `$ vim`
2. Focus the empty pane
3. Press Ctrl-P and open a file
4. File opens in NERDTree's pane

**Comment by sprt** [comment]
Turns out the problem isn't related to updatetime. I'll reopen when I find the cause.

**Comment by blayz3r** [comment]
The option let g:ctrlp_dont_split = 'NERD' works until you change the mode then it doesn't close nerdtree again.Anyone else have this issue
