### ISSUE TITLE
Can not find some file when use custom command

### ISSUE THREAD

**Issue by gngshn** [ctrlpvim/ctrlp.vim#287]
When I use custom command like `let g:ctrlp_user_command = 'find %s -type f'` or `let g:ctrlp_user_command = 'ag %s -f -U -l --nocolor -g ""'`, CtrlP will can not find mm/mmap.c in linux 4.4 source code, even though I type `mm/mmap.c`. CtrlP's result is like below when I type `mm/mmap.c`:

```
> arch/arm/mach-davinci/board-mityomapl138.c
> arch/arm/common/mcpm_platsmp.c
> arch/nios2/mm/dma-mapping.c
> arch/arm/mm/dma-mapping.c
> arch/powerpc/mm/mmap.c
> arch/s390/mm/mmap.c
> arch/tile/mm/mmap.c
> arch/x86/mm/mmap.c
> arch/arc/mm/mmap.c
> arch/arm/mm/mmap.c
```

On the other hand, I type `ag . -f -U -l --nocolor -g "" | grep 'mmap\.c'` in terminal, This file can find in the result.

```
$ ag . -f -U -l --nocolor -g "" | grep 'mmap\.c'
arch/powerpc/mm/mmap.c
arch/arm/mm/mmap.c
arch/tile/mm/mmap.c
arch/arc/mm/mmap.c
arch/x86/mm/mmap.c
arch/s390/mm/mmap.c
arch/sh/mm/mmap.c
arch/mips/mm/mmap.c
arch/arm64/mm/mmap.c
tools/testing/selftests/vm/hugepage-mmap.c
tools/build/feature/test-libelf-mmap.c
fs/ncpfs/mmap.c
fs/ocfs2/mmap.c
fs/ecryptfs/mmap.c
drivers/infiniband/hw/qib/qib_mmap.c
drivers/firmware/memmap.c
drivers/misc/mic/scif/scif_mmap.c
drivers/gpu/drm/nouveau/nvkm/subdev/bios/rammap.c
drivers/thermal/st/st_thermal_memmap.c
drivers/staging/rdma/hfi1/mmap.c
drivers/staging/rdma/ipath/ipath_mmap.c
drivers/staging/lustre/lustre/llite/llite_mmap.c
mm/sparse-vmemmap.c
mm/mmap.c
```

**Comment by gngshn** [comment]
I found when I search In regex mode, then type `mm/mmap.c`, CtrlP can find that file. If typying `mmap.c` only, CtrlP still can not find that file.

**Comment by mattn** [comment]
put this into your vimrc
```
let g:ctrlp_path_nolim = 1
```

**Comment by gngshn** [comment]
I have tried that. I does not work yet. the result is:
```
> arch/s390/mm/mmap.c
> arch/x86/mm/mmap.c
> arch/arc/mm/mmap.c
> arch/tile/mm/mmap.c
> arch/nios2/mm/dma-mapping.c
> arch/arm/mm/mmap.c
> arch/arm/mm/dma-mapping.c
> arch/arm/common/mcpm_platsmp.c
> arch/arm/mach-davinci/board-mityomapl138.c
> arch/powerpc/mm/mmap.c
```

**Comment by mattn** [comment]
you can scroll CtrlP window into up side.

**Comment by gngshn** [comment]
By <C-k>?, It does not work.

**Comment by gngshn** [comment]
In fact, if mm/mmap.c is get by ctrlp, it should display at bottom?

**Comment by mattn** [comment]
Yes, should be at bottom.

![](http://go-gyazo.appspot.com/f1d929c82f36b536.png)

**Comment by gngshn** [comment]
So what do you think about this issue. When use default function to find file, it work well. but if use user_commands, CtrlP does not show that file.

**Comment by mattn** [comment]
I don't reproduce with using ag.

**Comment by gngshn** [comment]
What is your ag command? can you tell me to have a try?

**Comment by mattn** [comment]
same as your's.

**Comment by gngshn** [comment]
.................
I am so sorry, may be It's a conflit with other config, I will check, then record it to here. Thinks a lot.

**Comment by gngshn** [comment]
Can you help me to reopen it, I close all other configs and plugins then test, It still have this problem.

**Comment by gngshn** [comment]
```
  % ag --version                                                                                                                                    !8197
ag version 0.32.0

Features:
  +jit +lzma +zlib



  % gvim --version                                                                                                                                  !8198
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52


![image](https://cloud.githubusercontent.com/assets/7463638/17512064/95de77f2-5e58-11e6-87d6-dbc027de5eb3.png)

```

**Comment by mattn** [comment]
what version of ag/vim do you use?

**Comment by gngshn** [comment]
Look at it before near your question

**Comment by mattn** [comment]
are you using latest ctrlp.vim?

**Comment by gngshn** [comment]
```
grant_shen@grant-pc ~/backup/vim/plugged/ctrlp.vim [master]
± % git remote -v                                                                                                                                   !8228
origin	https://git::@github.com/ctrlpvim/ctrlp.vim.git (fetch)
origin	https://git::@github.com/ctrlpvim/ctrlp.vim.git (push)

grant_shen@grant-pc ~/backup/vim/plugged/ctrlp.vim [master]
± % git pull                                                                                                                                        !8229
Current branch master is up to date.

```

**Comment by mattn** [comment]
Try to type F5?

**Comment by gngshn** [comment]
Linux grant-pc 3.19.0-65-generic #73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

This night, I will test it on my own notebook which OS is fedora 24.

I have tried `<F5>`, It does not work yet.

**Comment by gngshn** [comment]
How much time when you Index linux source folder?
If use ag is much faster than ctrlp default.

**Comment by mattn** [comment]
Could you please try `let g:ctrlp_match_natural_name = 1`

**Comment by gngshn** [comment]
Still have this problem when use `let g:ctrlp_match_natural_name = 1`

**Comment by mattn** [comment]
Reproduced it just now. Okay I'll look into it in later.

**Comment by gngshn** [comment]
Okay, Thank you very much.

**Comment by mattn** [comment]
BTW, did you try to type `<CTRL-d>` to disable directory mode?

**Comment by gngshn** [comment]
I had tried that, it also can not find mmap.c

**Comment by mattn** [comment]
I'll look into it. But if you want to resolve your issue immediately, you can use matcher. matcher is an extensible feature of CtrlP. One of the matcher, CPSM. https://github.com/nixprime/cpsm
CPSM is fastest matcher for CtrlP.

**Comment by gngshn** [comment]
ok, thanks for your information.

2016年8月9日 下午7:50，"mattn" <notifications@github.com>写道：

**Comment by gngshn** [comment]
On my notebook which used Fedora 24 does not have this problem. when I tap <C-p>, It display this:
```
> mm/memory_hotplug.c
> mm/page-writeback.c
> mm/kmemleak-test.c
> mm/memcontrol.c
> mm/zsmalloc.c
> mm/madvise.c
> mm/vmstat.c
> mm/mremap.c
> mm/zpool.c
> mm/util.c
```

**Comment by tjharman** [comment]
I can reproduce this issues on my Windows machine.

**Comment by BBonifield** [comment]
I can also reproduce this on macOS 10.12, ag 0.33.0, ctrl-p 1.79.  In my case, it's about finding `app/models/user.rb`.

I have the following configuration:

```
let g:ctrlp_user_command = 'ag %s -l --nocolor -g "" --depth 4'
let g:ctrlp_max_files = 15000
let g:ctrlp_use_caching = 0
```

When I type `app/models/user.rb`, I get the following results:

```
> app/models/client_upgrade_configuration/semantic_version.rb
> app/models/elements/configure_user_dashboard_element.rb
> app/models/elements/user_image_element.rb
> app/models/elements/user_note_element.rb
> app/models/landing_pages_user.rb
> app/models/oauth_consumer_app.rb
> app/models/onboarding_user.rb
> app/models/old_v1_user.rb
> app/models/cohort_user.rb
> app/models/guest_user.rb
```

I can find the file using regex mode, but all of the permutations of standard search won't find it.
