### ISSUE TITLE
Segmentation fault with neovim

### ISSUE THREAD

**Issue by balinterdi** [ctrlpvim/ctrlp.vim#288]
Invoking the :CtrlP command from neovim, it segfaults almost every time (it works very rarely, like once every 3 times).

I'd checked that it works with vim and even reinstalled neovim from scratch but it did not make a difference. I use Neovim 0.1.4 (installed from homebrew) on a Mac (OSX version 10.11.5).

**Comment by mattn** [comment]
Please report this issue to neovim. This is not an issue of CtrlP.

**Comment by balinterdi** [comment]
Fair enough, thank you.
