### ISSUE TITLE
Enter to create new file

### ISSUE THREAD

**Issue by lewmpk** [ctrlpvim/ctrlp.vim#290]
When i enter a file name that does not exits yet and then press ctrl+y, it creates the file as expected. But i'm trying to get the behaviour when i press CR(Enter) also. Currently, when i press CR with a file that doesn't exist yet, it does nothing.

**Comment by lewmpk** [comment]
so, after a bit of investigating...
CtrlP will not create the filename entered if you're in filename mode. I switched to MRU mode and pressing CR created the file. 

Is there a reason why we don't create the file in filename mode?

**Comment by mattn** [comment]
In latest, should be fixed.
