### ISSUE TITLE
Error using the new g:ctrlp_types

### ISSUE THREAD

**Issue by thylacinelol** [ctrlpvim/ctrlp.vim#293]
Hi,

After the latest changes, the following error is shown after launching vim:

_Error detected while processing ~/.vim/bundle/ctrlp.vim/autoload/ctrlp.vim:
line  211:
E121: Undefined variable: g:ctrlp_types
E116: Invalid arguments for function index(g:ctrlp_types, v:val[1])!=-1_

The commit which I'm using is d980d4d2759374c2750f21a8c3d099feac74cce5.

What more info is needed to debug this further?

**Comment by mattn** [comment]
Maybe your installation is wrong.

https://github.com/ctrlpvim/ctrlp.vim/blob/master/plugin/ctrlp.vim#L14-L18

**Comment by thylacinelol** [comment]
Sorry for the trouble. Found the issue.
It works after commenting the following line in **vimrc**:

_" ctrlp leaves stale caches behind if there is another vim process running
" which didn't use ctrlp. so we clear all caches on each new vim invocation
cal ctrlp#clra()_

Is this a bug or was this function deprecated?

**Comment by mattn** [comment]
Ah, I didn't consider it. Okay will fix soon.

**Comment by mattn** [comment]
should be fixed.

**Comment by thylacinelol** [comment]
Works great, thanks!

**Comment by mattn** [comment]
Thanks confirming.
