### ISSUE TITLE
Open file in current pane

### ISSUE THREAD

**Issue by spiffytech** [ctrlpvim/ctrlp.vim#296]
Can I make CtrlP open the selected file in the current pane, even if it's already open in another pane? I frequently want the same file open in multiple tabs, and _don't_ want to jump to the tab where the file is already open.

**Comment by tacahiroy** [comment]
The option, `let g:ctrlp_switch_buffer = 'et'`, should be working almost of cases. Can you try this?

**Comment by spiffytech** [comment]
Works for me. I submitted a pull request to add this to the docs.
