### ISSUE TITLE
Can ctrlp support file with Chinese name? Thank you!

### ISSUE THREAD

**Issue by xietren** [ctrlpvim/ctrlp.vim#297]
It seems that ctrlp does'nt work well with Chinese.
such as
 中文.txt 
 中文/中文路径/中文名.txt
How can I solve this problem? Thank you very much!

**Comment by tacahiroy** [comment]
Have you tried `let g:ctrlp_key_loop = 1`?

**Comment by xietren** [comment]
Thank you! 
I have it in my _vimrc all the time. It doesn't work.
I use WIN 7 os(x64) and VIM 7.4(x86).
This is my setting for CtrlP.
"---------------------------------------------------------
"ctrlp
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
"set wildignore+=*/tmp/*,*.so,*.swp,*.zip   " Linux/MacOSX
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe   "Windows
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn|rvm)$'
let g:ctrlp_working_path_mode=0
let g:ctrlp_match_window_bottom=1
let g:ctrlp_max_height=15
let g:ctrlp_match_window_reversed=0
let g:ctrlp_mruf_max=500
let g:ctrlp_follow_symlinks=1
let g:ctrlp_user_command = 'dir %s /-n /b /s /a-d'  " Windows
let g:ctrlp_key_loop=1
"

**Comment by mattn** [comment]
What do you mean `doesn't work` ?

**Comment by xietren** [comment]
@mattn My meaning is that
Setting `let g:ctrlp_key_loop=1` doesn't solve my problem about filepath with Chinese name?

**Comment by mattn** [comment]
Well, what do you mean ` doesn't solve my problem`. You still not explain your problem. :)

**Comment by xietren** [comment]
@mattn Sorry, let me describe my problem in another manner.
When I open CtrlP, my file such as "中文的书.txt" is displayed as "<bf><ec><bd>.txt".
SoHow to let CtrlP supports file with Chinese name?

**Comment by mattn** [comment]
What OS do you use?
What $LANG ?
What &encoding do you set on Vim? termencoding?

**Comment by mattn** [comment]
>Sorry,

No problem. :)

**Comment by xietren** [comment]
OS: win 7 (x64) 
GVIM: 7.4 (x86)
I set enoding=utf-8 
Here is encoding setting in my _vimrc:
```
if has("multi_byte")
    "设置编码自动识别，中文引号显示
    set encoding=utf-8
    let &termencoding=&encoding
    set formatoptions+=mM
    set fileencodings=ucs-bom,utf-8,gbk,cp936,gb18030,big5,gb2312,chinese,latin-1
    if v:lang =~? '^/(zh/)/|/(ja/)/|/(ko/)'
        set ambiwidth=double
    endif
    if has("win32")
        "解决菜单乱码
        source $VIMRUNTIME/delmenu.vim
        source $VIMRUNTIME/menu.vim
        "解决consle输出乱码
        language messages zh_CN.utf-8
    endif
else
    echoerr "This version of (g)vim was not compiled with +multi_byte"
endif
```

**Comment by mattn** [comment]
Try to unlet `g:ctrlp_user_command`

**Comment by xietren** [comment]
@mattn @tacahiroy  Thank you very much!
I should comment this command  `let g:ctrlp_working_path_mode=0`.

**Comment by mattn** [comment]
> I should comment this command let g:ctrlp_working_path_mode=0.

Do you fix your problem, don't you?

**Comment by xietren** [comment]
@mattn  Yes, my problem is fixed using your idea.

**Comment by wogong** [comment]
> Have you tried `let g:ctrlp_key_loop = 1`?

This setting solved my problem, thanks!
