### ISSUE TITLE
Custom Mappings for Opening Files not Working

### ISSUE THREAD

**Issue by johnnyji** [ctrlpvim/ctrlp.vim#301]
Hi there,

I have the following in my vimrc:

```
let g:ctrlp_prompt_mappings = {
	\ 'AcceptSelection("v")': ['<c-i>', '<RightMouse>'],
	\ }
```

Which I assume is supposed to open a file in vertical split pane when I type `Ctrl i` in the prompt. But this is not working... However it does make `c-v` stop working... So I guess it's partially there.

Does anyone have any ideas why that might be?

PS Thanks for the amazing plugin!

**Comment by mattn** [comment]
`<c-i>` mean `<tab>` in terminal (also implemented also on gvim). And `<tab>` is already assigned to `PrtExpandDir`. So you need to avoid dup like below.

```vim
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("v")': ["<tab>", '<RightMouse>'],
	\ 'PrtExpandDir()':       ['<s-tab>'],
    \ }
```

**Comment by johnnyji** [comment]
@mattn Wow I had no idea. Thanks a lot for the prompt response 👍
