### ISSUE TITLE
How to change/disable default mappings?

### ISSUE THREAD

**Issue by dawnofthedev** [ctrlpvim/ctrlp.vim#306]
Is it possible to disable all default triggers of ctrlp?  Or at least, how do I disable the default 'Enter' behavior bringing up CtrlP? It's annoying, e.g. now in quickfix Enter doesn't select an entry, it opens CtrlP!

Please help... How has nobody else complained about Enter being overridden in quickfix/locationlist?

**Comment by mattn** [comment]
What's your goal? For example, remaining CtrlP on bottom window?

**Comment by dawnofthedev** [comment]
I want the option to disable any 'out of the box' normal mode mappings and add only what I want. 

The specific reason is the new behavior of pressing 'Enter' in normal mode - it shows the MRU ctrlp list. But that's annoying... E.g. if I am working in the quickfix window and press Enter to select an item, all that happens is MRU list shows up beneath it.

**Comment by mattn** [comment]
You can modify the action with `ctrlp_open_func`.

**Comment by dawnofthedev** [comment]
Thanks but you misunderstand. I want to disable <CR> in normal mode from opening CtrlP.

**Comment by mattn** [comment]
Hmm, still I don't really understand what is your goal. In my understanding, you are mapping `<CR>` in normal mode to open CtrlPMRUFiles. But it's not work on CtrlP's prompt. Right?

**Comment by mattn** [comment]
If you want to change behavior of `<cr>` in CtrlP's prompt, you can try this.
```
let g:ctrlp_prompt_mappings = {
\ 'AcceptSelection("e")': ['<c-e>'],
\}
```
This change assign of key to open the file.

**Comment by dawnofthedev** [comment]
Thanks for responses. Ok let me try to explain more clearly.

Suppose I start up vim (I see a blank screen). I don't do anything else. I press CR. Ctrlp opens and then I see the MRU list. I don't want that. I want Ctrlp to leave all my keys alone and let me decide what the triggers to start Ctrlp should be.

**Comment by mattn** [comment]
CtrlP doesn't provide mapping `<CR>` in normal mode. Try to confirm where make the mapping.

```
verbose map <CR>
```

**Comment by dawnofthedev** [comment]
I apologize, I had this in my vimrc
`nnoremap <C-m> :CtrlPMRU<CR>`
And this was mapping `<CR>` somehow.
Thanks for the help @mattn
