### ISSUE TITLE
keymap

### ISSUE THREAD

**Issue by habamax** [ctrlpvim/ctrlp.vim#307]
How can you change keymap while in ctrlp?

Usually it is done using `Ctrl-^` but ctrlp binds it to `move left`.

I cannot find non-english filenames.

I have also tried to remove that binding from ctrlp, but it looks like input line is not in insert mode, so `Ctrl-^` tries to open alternate file.

**Comment by mattn** [comment]
Try to set `let g:ctrlp_key_loop = 1`.

**Comment by habamax** [comment]
without removing `C-^`: goes back one char on a prompt

with removing it: nothing happens (but no tries to open alternate file)

**Comment by mattn** [comment]
I mean the `let g:ctrlp_key_loop = 1` will fixes your issue above.

> I cannot find non-english filenames.

**Comment by habamax** [comment]
Well, yes, with this I can switch OS input method and be able to find nonenglish filenames. Thx!

Although, in vim I usually avoid using OS input switcher. Is it possible to use keymaps with CtrlP?

**Comment by mattn** [comment]
> Is it possible to use keymaps with CtrlP?

No. CtrlP is designed that can be assign key mappings to the feature only provide from CtrlP.

**Comment by habamax** [comment]
>CtrlP is designed that can be assign key mappings to the feature only provide from CtrlP.

Not sure I understand that part. But I can see that CtrlP is not in insert mode when you type something in. And keymaps are for insert mode, for searches, and :commands.

Okay then, anyway thx!

**Comment by mattn** [comment]
If you want the new feature on the prompt of CtrlP, we may be possible toimplement it. :) And patches welcome.

**Comment by habamax** [comment]
I have just looked into the code and now I get what you mean by ctrlp mappings. It overrides buffer local normal map with subset of ascii symbols. I am not sure about patches but let me investigate more
