### ISSUE TITLE
CtrlP not finding entries in VIM 80.

### ISSUE THREAD

**Issue by mboughaba** [ctrlpvim/ctrlp.vim#308]
Hello,

Not sure if this is due to CtrlP itself or a change in the new major version 80 of vim.
After upgrading vim, CtrlP is not matching any files.
Refreshed the CtrlP cache but that didn't help.
Any help or guidance will be welcome.

**Comment by mattn** [comment]
At the first, please try to disable all plugins without CtrlP, And make small vimrc to reproduce.

**Comment by mboughaba** [comment]
CtrlP itself is working properly.
The problem comes from using `let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }`
