### ISSUE TITLE
Support for including only certain files

### ISSUE THREAD

**Issue by joshpfosi** [ctrlpvim/ctrlp.vim#312]
Hi I am working in a project with 200k + files in a given workspace but only a small fraction which I need access to at a given time. I see the option to configure dirs which I want to ignore, but it is tedious to ignore the many directories just to search 1-3. I would much prefer to specify a positive regex e.g. `g:ctrlp_custom_include`. Is this possible?

**Comment by mattn** [comment]
For example?

**Comment by joshpfosi** [comment]
The format would be identical only the semantics would differ. E.g.

```shell
let g:ctrlp_custom_ignore = '\v[\/](dirA|dirB|dirC)$' # do not search in dir{A,B,C}
let g:ctrlp_custom_include = '\v[\/](dirA|dirB|dirC)$' # search only in dir{A,B,C}
```

**Comment by mattn** [comment]
CtrlP get the list of files from external command. So if you have over 200k files, the stream will be fuge. To ignore this, you should specify option to the command to ignore your want, Or filter with grep to collect you want.

**Comment by joshpfosi** [comment]
Can you give an example of this? Nothing I have tried is successful.

My project has the following format `/src/{dirA,dirB,dirC}`, where / is the root directory via `chroot` and I want to look in `dirA,B,C` but `/` and `/src` contain many other directories besides.

I've tried things like:

`let g:ctrlp_user_command='find /src/dirA /src/dirB -type f'`

My project is under p4 for VCS and I have tried using p4 files as well without any luck...

**Comment by mattn** [comment]
> let g:ctrlp_user_command='find /src/dirA /src/dirB -type f'

Is not this your expected?

**Comment by joshpfosi** [comment]
No this does not work for me. I get "no entries".

**Comment by tacahiroy** [comment]
@mattn 
Although I haven't looked at this deeply yet, as I have debugged, `E767: Too many arguments to printf()` occurs inside of the block of [ctrlp.vim#L451](https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L451), coz there is no % items is in the 1st argument, `find /src/dirA /src/dirB -type f` in this case.

**Comment by joshpfosi** [comment]
Yeah I figured it had to with that. I would really prefer to do absolute paths though as the code base is sprawling and I rarely intend to search in the current directory and often times am looking for a file in a totally other root (e.g. current dir is dirA but I need a file from dirB, continuing with my example from above).

**Comment by mattn** [comment]
how about this? 

```
let g:ctrlp_user_command='find /src/dirA /src/dirB -type f && true %s'
```

**Comment by joshpfosi** [comment]
Works like a dream :) Thank you.
