### ISSUE TITLE
Add Dev Icon Integration

### ISSUE THREAD

**Issue by F1LT3R** [ctrlpvim/ctrlp.vim#313]
I used to use NERDTree often, but I find more-and-more that Ctrl-P is a much better fit for how Vim buffers work. However, with Ctrl-P, I loose the immediate visual context that is provided by [Dev Icons](https://github.com/ryanoasis/vim-devicons). 

It would be lovely to have Ctrl-P use Dev Icons, like NERDTree does. (Currently it only works in MRU mode.)

Any ideas how painful/easy it would be to provide extensions to make dev-icons more integratabtle?

**Comment by mattn** [comment]
CtrlP have already integration for DevIcon.

See https://github.com/ctrlpvim/ctrlp.vim/issues/267

**Comment by F1LT3R** [comment]
CtrlP seems to only work with Dev Icons for MRU (Most Recently Used files list).

As far as I can tell this is a limitation with the ability to format the other modes, but perhaps I am barking up the wrong tree here.

**Comment by mattn** [comment]
@ryanoasis I'm not user of devicon. Do you have know-how about installation instruction about this?

**Comment by ryanoasis** [comment]
@mattn Sure 😄 

@F1LT3R Actually it does support all modes now as long as you have the latest versions of ctrlp and vimdevicons. This was made possible after #267 as @mattn mentioned.

You are bother right that the readme is out of date. It still says MRU mode only but in reality it should now support all modes

**Comment by F1LT3R** [comment]
Ah thanks! Dev-Icons did not work for me outside MRU mode. But after re-installing these plugins just now, I get do Dev-Icons outside of MRU mode. Apologies for any time wasted. 

I'll send you a documentation PR if you like @ryanoasis ?

We should close this.

**Comment by mattn** [comment]
I'
