### ISSUE TITLE
:CtrlPMixed doesn't detect duplicates

### ISSUE THREAD

**Issue by timfeirg** [ctrlpvim/ctrlp.vim#314]
When using `:CtrlPMixed`, results shows many duplicate files, while `:CtrlP` works fine

<img width="260" alt="good" src="https://cloud.githubusercontent.com/assets/4319104/18392805/c63765bc-76e5-11e6-9d21-a647588eb983.png">

<img width="244" alt="bad" src="https://cloud.githubusercontent.com/assets/4319104/18392807/ce672d08-76e5-11e6-8e67-6220f018be19.png">

I believe this issue emerged recently, but I haven't been able to determine the exact commit that causes this.

**Comment by mattn** [comment]
could you please how to repro.

**Comment by timfeirg** [comment]
To reproduce, just open up vim with ctrlp loaded, and then use `:CtrlPMixed` and open up some files, do this for a few times, so that one of the files appears both in files and MRU, after this, `:CtrlPMixed` will show duplicate items @mattn 

I tried to filter duplicates using a dictionary, but this method breaks the order of list.
