### ISSUE TITLE
Change Ctrlp activation from control + p to control + k

### ISSUE THREAD

**Issue by nikitavoloboev** [ctrlpvim/ctrlp.vim#315]
I thought that adding these lines to vimrc would work : 

```
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
```

But it doesn't.

**Comment by mattn** [comment]
confirm whether your installation is correctly.

```
:map <c-p>
```

**Comment by nikitavoloboev** [comment]
After adding this line to vimrc and restarting vim I get this error

https://i.imgur.com/pLEwhOB.png

**Comment by nikitavoloboev** [comment]
It runs fine with control + p though, I just want to remap it to control + k

**Comment by nikitavoloboev** [comment]
All right, I think I figured it out. Thank you for the help.
