### ISSUE TITLE
Follow .gitignore in Windows (PowerShell)

### ISSUE THREAD

**Issue by mcandre** [ctrlpvim/ctrlp.vim#317]
How should ctrlp be configured so that .gitignore is respected, even in Windows/PowerShell environments?

**Comment by mattn** [comment]
set `g:ctrlp_user_command` for the external command which handle `.gitignore`

**Comment by mcandre** [comment]
I tried setting ctrlp_user_command according to the README, and even cleared my ctrlp cache, but node_modules still shows up in ctrlp results.

In Windows/PowerShell, the only thing that works for me is `set wildignore+=node_modules`, though that's annoying to do for multiple gitignore patterns

**Comment by mattn** [comment]
If you want to list the files managed by git, 

```
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
```

**Comment by mattn** [comment]
should be resolved.
