### ISSUE TITLE
Hiding the CtrlP statusline

### ISSUE THREAD

**Issue by manasthakur** [ctrlpvim/ctrlp.vim#321]
I want to hide the CtrlP statusline altogether. I got the following solution at kien/ctrlp.vim/issues/413:
```
let g:ctrlp_buffer_func = {
    \ 'enter': 'Function_Name_1',
    \ 'exit':  'Function_Name_2',
    \ }

func! Function_Name_1()
    set laststatus=0
endfunc

func! Function_Name_2()
    set laststatus=2
endfunc
```

However, considering that it's a very old post (on the previous fork of CtrlP), is there a simpler solution available now that I am not aware of?

**Comment by tacahiroy** [comment]
ctrlp doesn't provide "no statusline" option yet, so this is still the only workaround.

**Comment by manasthakur** [comment]
Okay. CtrlP is the best vim-plugin out there anyway :+1:
