### ISSUE TITLE
What is this "NULL" in CtrlPBuffer?

### ISSUE THREAD

**Issue by manasthakur** [ctrlpvim/ctrlp.vim#325]
Hi!

I get a "NULL" written after the name of the open buffers (before the file location) when I use CtrlPBuffer (screenshot attached). What could be the reason?
![screen shot 2016-11-18 at 3 00 26 pm](https://cloud.githubusercontent.com/assets/5248710/20425276/ea5ca1f0-ad9f-11e6-9539-8f815e659486.png)

Regards,
Manas

**Comment by mattn** [comment]
what is your OS, version of vim, plugins, vimrc?

**Comment by manasthakur** [comment]
macOS. Vim 7.4. I have tried disabling all other plugins; doesn't help.
My CtrlP configuration is as follows:
```
nnoremap <silent><leader>b :CtrlPBuffer<CR>
nnoremap <silent><leader>r :CtrlPMRUFiles<CR>
nnoremap <silent><leader>t :CtrlPBufTag<CR>
let g:ctrlp_custom_ignore = '.svn\|.hg\|.git\|build\|*.o\|*.class'
let g:ctrlp_working_path_mode = 'a'     "Search only from the current directory
let g:ctrlp_buffer_func = {
    \ 'enter': 'DisableStatus',
    \ 'exit':  'EnableStatus',
    \ }
function! DisableStatus()
    set laststatus=0
endfunction
function! EnableStatus()
    set laststatus=2
endfunction
```

Interestingly, with the same set of plugins and vim version, this does not happen on a Fedora machine.

**Comment by mattn** [comment]
thank you but don't reproduce.

**Comment by tacahiroy** [comment]
This is happened if Vim compiled without `conceal` feature. An extra expr given for `printf` in that case.

**Comment by tacahiroy** [comment]
I've just merged the fix into master. https://github.com/ctrlpvim/ctrlp.vim/commit/d9eb5aecab74db300bdf2c76308b2c02c469cf5e
