### ISSUE TITLE
Can't navigate the result list

### ISSUE THREAD

**Issue by EdvinOlofsson** [ctrlpvim/ctrlp.vim#326]
Hello!

I'm unable to navigate the result list. Neither the <c-j>, <c-k> or the arrow keys <Up>, <Down> works.
`:verbose map <Up>` gives "No mapping found"
`:verbose map <Down>` gives "No mapping found"

Any ides on how to solve this issue?

I could not find any documentation on remapping the movement keys. Is this possible?

Kind Regards
Edvin

**Comment by tacahiroy** [comment]
You can achieve that like this:
```vim
let g:ctrlp_prompt_mappings = {
    \ 'PrtSelectMove("j")':   ['<down>'],
    \ 'PrtSelectMove("k")':   ['<up>']
    \ }
```
See `:h g:ctrlp_prompt_mappings` more defails
