### ISSUE TITLE
Will there be releases?

### ISSUE THREAD

**Issue by lucc** [ctrlpvim/ctrlp.vim#327]
The last release (git tag) was still on the original repo by kien. Are you planing to tag releases any time/soon?

It would be an advantage for distributions that might want to package this plugin. Eg see https://bugs.archlinux.org/task/45570

**Comment by lucc** [comment]
Thank you. Can you also add a tag to that commit so github will treat it as a release.

**Comment by mattn** [comment]
okay. will do.

**Comment by tacahiroy** [comment]
@mattn I've tagged as 1.80 for the current HEAD, 2868678a.

**Comment by mattn** [comment]
@tacahiroy Yes, thank you. @lucc mentioned about next release. :)

**Comment by tacahiroy** [comment]
oops :|
-- 

Takahiro Yoshihara
tacahiroy@gmail
