### ISSUE TITLE
Only 10 files are showing

### ISSUE THREAD

**Issue by lokesh1729** [ctrlpvim/ctrlp.vim#330]
Hey,

I have nearly 60 files matching a name in my project, but ctrlP only showing 10 files. is there any option to set to show all??

**Comment by mattn** [comment]
you OS? version of vim? you vimrc?

**Comment by lokesh1729** [comment]
OS : ubuntu 16.04
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

my vimrc:
https://raw.githubusercontent.com/lokesh1729/myPython/master/vimconfig

**Comment by mattn** [comment]
Do you mean `only showing 10 files`? or `window height is 10`? You can modify the height with `g:ctrlp_max_height`. If you mean first, you can type something to match files.

**Comment by lokesh1729** [comment]
I am absolute beginner in vim, I am having a large project, if I search for models.py it is showing only 10 files, Also I set the window height to 100, but still it's not showing all matching files.

**Comment by mattn** [comment]
default value of g:ctrlp_max_height is 10. You can type something to match.
![terminal](https://cloud.githubusercontent.com/assets/10111/20697363/f865c1c4-b63b-11e6-88fa-6dc0e9ff2d8e.gif)

**Comment by lokesh1729** [comment]
yeah, but let's say we have more files matching the file, then we should able to scroll through all the files, isn't it available in vim???

**Comment by mattn** [comment]
try `let g:ctrlp_path_nolim = 1`

**Comment by lokesh1729** [comment]
No, not working...

**Comment by mattn** [comment]
What do you mean `not working`? What did you do?

**Comment by lokesh1729** [comment]
I put let g:ctrlp_path_nolim = 1 in vimrc, then tried to find models.py in my project, it's still showing 10 files, I am not able to scroll up or down through all the files that matching

**Comment by mattn** [comment]
If you have match some, ctrlp can't scroll up/down matches. but you can do filter with query.

**Comment by lokesh1729** [comment]
Ohh is it... Okay... Can I close this issue?

**Comment by mattn** [comment]
if you solve the issue.

**Comment by lokesh1729** [comment]
No I can't, I don't even know the basics of writing vim plugins....

**Comment by tacahiroy** [comment]
According to the [vimrc](https://raw.githubusercontent.com/lokesh1729/myPython/master/vimconfig) file you put above, you use the original ctrlp.vim (kien version) which is too old and not maintained any more.
It is strongly suggested to use the latest one [ctrlpvim/ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim).

**Comment by lokesh1729** [comment]
I modified it, but still the problem is there

**Comment by mattn** [comment]
As I said in above, this is not problem. This is expected behavior.

**Comment by lokesh1729** [comment]
Okay...
