### ISSUE TITLE
Confusing g:ctrlp_root_markers behavior

### ISSUE THREAD

**Issue by tardypad** [ctrlpvim/ctrlp.vim#333]
I was trying to use this variable but the information regarding the order the markers are searched, present in the README is different from the one in the Doc

README says the additional markers are searched **after** the default ones
```
If none of the default markers (.git .hg .svn .bzr _darcs) are present in a project, you can define additional ones with g:ctrlp_root_markers:
let g:ctrlp_root_markers = ['pom.xml', '.p4ignore']
If more than one mode is specified, they will be tried in order until a directory is located.
```

Doc says the additional markers are searched **before** the default ones
```
Use this to set your own root markers in addition to the default ones (.git,
.hg, .svn, .bzr, and _darcs). Your markers will take precedence: >
  let g:ctrlp_root_markers = ['']
```

From my tests, the actual behavior is the one as defined in the README
However, I would have wanted to get the behavior defined in the Doc
And this seems to be what other people needed too
https://www.reddit.com/r/vim/comments/308v8i/how_to_add_multiple_git_projects_to_ctrlp_search/

**Comment by mattn** [comment]
As far as I see the code, root marker is finding in this order.

* finding markers in ctrlp_root_markers (if defined)
* finding .git, .hg, .svn, .bzr, _darcs

**Comment by tardypad** [comment]
I've tried to reproduce the same behavior as described in the link I've previously sent
But it doesn't behave as if the `ctrlp_root_markers` as looked for first

I've reduced my CtrlP settings to only
`let g:ctrlp_root_markers = [ '.ctrlp' ]`

and here is the initial folder structure
```
├── .ctrlp
├── repo_1
│   ├── file_1_1
│   ├── file_1_2
│   └── .git
└── repo_2
    ├── file_2_1
    ├── file_2_2
    └── .git
```

Now if I execute `vim repo_1/file_1_1` and launch CtrlP, the file list is
```
file_1_2
```

then I remove `repo_1/.git`
and execute the same `vim repo_1/file_1_1` and launch CtrlP, the file list is
```
repo_2/file_2_2
repo_2/file_2_1
repo_1/file_1_2
```

Here is a small test script for all this
```
mkdir ctrlp_marker_test
touch ctrlp_marker_test/.ctrlp
mkdir ctrlp_marker_test/repo_1
touch ctrlp_marker_test/repo_1/.git
touch ctrlp_marker_test/repo_1/file_1_1 ctrlp_marker_test/repo_1/file_1_2
mkdir ctrlp_marker_test/repo_2
touch ctrlp_marker_test/repo_2/file_2_1 ctrlp_marker_test/repo_2/file_2_2
touch ctrlp_marker_test/repo_2/.git

vim ctrlp_marker_test/repo_1/file_1_1 +CtrlP

rm ctrlp_marker_test/repo_1/.git

vim ctrlp_marker_test/repo_1/file_1_1 +CtrlP
```

**Comment by RobertBuhren** [comment]
I'm experiencing the same problem. I have a project that consists of several git repos and I'm not able to search them all as Ctlrp will stop looking for futher file as soon as it found a .git folder.

**Comment by mattn** [comment]
do you set autochdir?

**Comment by RobertBuhren** [comment]
No, autochdir is set to "noautochdir"

**Comment by mattn** [comment]
Ah, I was confused. You mean how to recognize multiple .git directory?

**Comment by RobertBuhren** [comment]
I have a directory structure like this:

├── .ctrlp
├── repo_1
│   ├── file_1_1
│   ├── file_1_2
│   └── .git
└── repo_2
    ├── file_2_1
    ├── file_2_2
    └── .git

When I execute Ctlrp fom inside e.g. repo2 CtrlP will not includes files from repo1 even if I set let g:ctrlp_root_markers = [ '.ctrlp' ]

I want CtrlP to include all folders up the dir structure until the ".ctrlp" file is found, regardless of whether a ".git" folder was found before or not.

Regards,

Robert

**Comment by mattn** [comment]
Thanks. I just really understand.

**Comment by RobertBuhren** [comment]
Will this behaviour change in future version?

**Comment by mattn** [comment]
Will do. please wait.

**Comment by RobertBuhren** [comment]
Thx :)

**Comment by mattn** [comment]
Could you pleaes try this?

```diff
diff --git a/autoload/ctrlp.vim b/autoload/ctrlp.vim
index 6558939..d5b11a0 100644
--- a/autoload/ctrlp.vim
+++ b/autoload/ctrlp.vim
@@ -1763,6 +1763,7 @@ fu! ctrlp#setpathmode(pmode, ...)
 		let spath = a:0 ? a:1 : s:crfpath
 		let markers = ['.git', '.hg', '.svn', '.bzr', '_darcs']
 		if type(s:rmarkers) == 3 && !empty(s:rmarkers)
+			if s:findroot(spath, s:rmarkers, 0, 0) != [] | retu 1 | en
 			cal filter(markers, 'index(s:rmarkers, v:val) < 0')
 			let markers = s:rmarkers + markers
 		en
```

**Comment by RobertBuhren** [comment]
Sorry for the long delay. 
I just tested this patch, but it didn't work. CtrlP still seems to stop traversing the directory hierarchy as soon as it finds e.g. a .git folder

**Comment by mattn** [comment]
As far as I try this, CtrlP stopped at .ctrlp

**Comment by tardypad** [comment]
Sorry for the delay too, I've just tested myself that patch now
Seems to work fine for me :+1: 

@RobertBuhren maybe you have some other ctrlp config that conflicts with this setting?
Like a different ctrlp_cmd or so, which makes it ignore ctrlp_working_path_mode.
You should try with only `let g:ctrlp_root_markers = [ '.ctrlp' ]` set to be sure
