### ISSUE TITLE
Support Vim 8.0 feature to avoid vim getting stuck

### ISSUE THREAD

**Issue by skywind3000** [ctrlpvim/ctrlp.vim#337]
CtrlP is a great plugin, but still not so perfect (comparing to similar function in IDEs or Emacs):
Vim always get unresponsive for a very noticable time when I'm opening CtrlP.

It would be very nice if CtrlP can refresh incrementally.

Possible solution: Incremental Collecting in a timer ?

Divide the whole file collecting job into pieces, and put them in timers (eg, a 20Hz interval), analyse fixed amount of files in an interval than refresh the ctrlp incrementally (just like similar plugins in emacs/IDE).

------------
Wish CtrlP can work perfectly just like Emacs/IDEs.

**Comment by prabirshrestha** [comment]
This is a setting I now use found it to be very fast.

```viml
let g:user_command_async = 1
if executable('rg')
  let g:ctrlp_user_command = 'rg --files -F --color never --hidden --follow --glob "!.git/*" %s'
endif
```

If rg is fast enough you can also disable ctrlp caching. `let g:ctrlp_use_caching = 0`

**Comment by mattn** [comment]
CtrlP has already ctrlp_user_command_async.
