### ISSUE TITLE
support for infinite results

### ISSUE THREAD

**Issue by prabirshrestha** [ctrlpvim/ctrlp.vim#338]
Currently I need to use this.

```
let g:ctrlp_match_window = 'results:100000'
```

It would be great if I could set `results:-1` or `results:0`, so I don't have to put a very large number.

**Comment by mattn** [comment]
yes, results:0 should mean you want.

**Comment by mattn** [comment]
Ah, sorry. figure out now.

**Comment by m1713u** [comment]
O
