### ISSUE TITLE
buffertag compatibility with universal ctags

### ISSUE THREAD

**Issue by IngoHeimbach** [ctrlpvim/ctrlp.vim#339]
Hey,
I have recognized that the buffertag extension is not fully compatible with the new [universal ctags](https://ctags.io/). Tags with file scope (for example static functions in C) are ignored when universal ctags is run whereas exuberant ctags works fine. 

In [buffertag.vim](https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp/buffertag.vim#L142) `ctags` is called with an empty `--extra=` argument. With exuberant ctags that's fine but universal ctags has introduced a new `F` extra value that enables file scoped tags and is on by default. `--extra=` disables that behavior and file scoped tags are not generated any more. Is it really necessary to deactivate all `extra` flags?

**Comment by mattn** [comment]
@majutsushi can you handle this?

**Comment by majutsushi** [comment]
For this simple case what I did in Tagbar is just add the `--file-scope=yes` command line argument to the ctags call which makes it work with both Exuberant Ctags and Universal Ctags. For the more general case of supporting both main ctags implementations and "third-party" language-specific tools I'm currently working on a library that plugins that want to use tags like Tagbar and CtrlP can use, but I don't know yet when it will be ready.

**Comment by Taverius** [comment]
*poke*

Any chance of this happening?

Took a look at `buftag` and it looks like the only real question is what `jsctags` would do with `--file-scope=yes`.

**Comment by majutsushi** [comment]
I have just created pull request #372 to fix the simple case. `jsctags` shouldn't be affected in any case since file-specific executables are configured separately.

**Comment by mattn** [comment]
closed by #372 . if you still have issue, please reopen this.
