### ISSUE TITLE
CtrlPLine matches are not highlighted

### ISSUE THREAD

**Issue by stormherz** [ctrlpvim/ctrlp.vim#341]
In line mode matched characters are not highlighted like in buffer of file modes, is it intended to be so?

Line mode without highlighted `some` matches:
<img width="411" alt="screen shot 2017-01-09 at 02 52 56" src="https://cloud.githubusercontent.com/assets/235075/21753078/05866ac0-d617-11e6-859f-6b85f0ed44a7.png">

File mode with correct highlighting:
<img width="397" alt="screen shot 2017-01-09 at 02 53 53" src="https://cloud.githubusercontent.com/assets/235075/21753077/0585dac4-d617-11e6-9d42-452ec8a0f215.png">

**Comment by tacahiroy** [comment]
Unfortunately, the highlight matched characters feature is supported for `path` mode only atm.
