### ISSUE TITLE
dot folders are ignored

### ISSUE THREAD

**Issue by whitecolor** [ctrlpvim/ctrlp.vim#344]
I have custom ignore:
```
   let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
```

But files in folders that starts with `.` are not shown. How this can be fixed?

Though I've set `g:ctrlp_show_hidden = 1`.

**Comment by whitecolor** [comment]
Worked, probably due to setting `g:ctrlp_show_hidden`.

**Comment by chris-fran** [comment]
Didn't work for me

**Comment by Felixoid** [comment]
Should add here, that if you first have opened ctrlP before setting `g:ctrlp_show_hidden`, you must reload the cache with `F5`
