### ISSUE TITLE
CtrlP Crash if Ctrl+S pressed on results window

### ISSUE THREAD

**Issue by adeelcap15** [ctrlpvim/ctrlp.vim#352]
In the result window, if i want to open file in vertical split, I press Ctrl + V and its working fine. But if I wants to open file in horizontal split, i press Ctrl + S and the vim is not responding.

**Comment by mattn** [comment]
What version of vim do you use? OS? plugins?

**Comment by adeelcap15** [comment]
OS:          Ubuntu LTS 16.04
Vim:         7.4
**Plugins**:   
ctrlp.vim,  emmet-vim, nerdtree, syntastic, tabular, ultisnips
vim-commentary, vim-fugitive, vim-snippets, vim-surround
I have also disabled all plugins except ctrlp and the bug can still be reproduced.

**Comment by mattn** [comment]
What do you mean `crash`? segmentation fault? signal received? hang?

**Comment by wsdjeg** [comment]
it is feature of bash, you can use `ctrl+q` to remove the status of `ctrl+s`.

**Comment by wsdjeg** [comment]
https://en.wikipedia.org/wiki/Software_flow_control

**Comment by adeelcap15** [comment]
it actually hangs. But pressing ctrl+q, it will be responsive again.

**Comment by wsdjeg** [comment]
so you can read the link above, it is feature of bash.

**Comment by wsdjeg** [comment]
also this would be easy to understand

https://unix.stackexchange.com/questions/137842/what-is-the-point-of-ctrl-s
