### ISSUE TITLE
With huge code base, the fuzzy finder is quite dumb

### ISSUE THREAD

**Issue by MightyCreak** [ctrlpvim/ctrlp.vim#356]
I have a base code of 48000 files.
I hit C-P and write exactly the name of the file I want to open, I even hit C-D to match files only.
The proposed answer are all but the file I'm asking for.

The problem is that there are too many results for the window to display, but also that the results don't seem to be ordered by relevance.

I think that when I search for "myclass.cs", the result "MyClass.cs" is more relevant than "MyDerivedClass.cs". Not by much, but still more relevant.

Right now, it seems that the order when browsing the files is deciding of the relevance of the results.

Or maybe there's an option I haven't seen?

**Comment by MightyCreak** [comment]
Dup #318

**Comment by Yggdroot** [comment]
Why not try my plugin [LeaderF](https://github.com/Yggdroot/LeaderF), I think it can solve your problem.

**Comment by MightyCreak** [comment]
Interesting... Thanks @Yggdroot !

**Comment by mattn** [comment]
@Yggdroot Hey, STOP introducing your project here.

**Comment by Yggdroot** [comment]
I just told @MightyCreak , did not reply at issue 318.

**Comment by mattn** [comment]
Then do it at another space not here. Do you understand what I mean?

**Comment by Yggdroot** [comment]
Sorry, OK.

**Comment by MightyCreak** [comment]
All that being said, I think that the best would be that the two project merged.

CtrlP has its pros and cons, as much as LeaderF. It sad that the user has to chose between those two.
And it's sadder that this is the case for each and every plugins...

If you don't merge, at least take the best ideas from the other project ;)

**Comment by sisrfeng** [comment]
LeaderF has similar problem, worse than raw ripgrep
