### ISSUE TITLE
Attempting to update through plug throws git error for ctrl + p

### ISSUE THREAD

**Issue by Zerophase** [ctrlpvim/ctrlp.vim#362]
I just started getting a git error, whenever I try to update plug. Is it an issue with repo permissions?

>     remote: Counting objects: 12, done.        
>     remote: Compressing objects: 100% (8/8), done.        
>     remote: Total 12 (delta 6), reused 10 (delta 4), pack-reused 0        
>     error: insufficient permission for adding an object to repository database .git/objects
>     fatal: failed to write object
>     fatal: unpack-objects failed

**Comment by mattn** [comment]
I don't know why. Maybe you did `:PlugUpdate` with sudo. Anyway, it's not depend on CtrlP.
