### ISSUE TITLE
CtrlP undoes most recent change

### ISSUE THREAD

**Issue by GabeIsman** [ctrlpvim/ctrlp.vim#363]
I just updated my plugins today and discovered to my horror that work my was disappearing as I navigated away from a file. I narrowed this down to a minimal vimrc which still produces this behavior:

```
filetype off                  " required for Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim' 
call vundle#end()            " required
filetype plugin indent on    " required
```

To reproduce: 
1. Make an insertion in a new file.
2. Invoke CtrlP with `<c-r>-p`.
3. Observe that whatever you just typed is gone.

Things I noticed when exploring this:
1. It's only insertions. Deletions don't get reverted (changes do). Pastes don't, etc.
2. The text comes back if you escape out of CtrlP and invoke it again. (It disappears again if you repeat, and so on.)

**Comment by GabeIsman** [comment]
I can confirm that I reverted back to 7fa89fec125ce60a341f7c37dd769a8a31c49359 (chosen by complete guesswork as being long enough ago) and the problem disappeared. So the bug was introduced somewhere in the last 12 commits or so.

**Comment by silverlyra** [comment]
@GabeIsman 🙏 thank you! I thought I was losing my mind

**Comment by mattn** [comment]
Could you please this change?

```
diff --git a/autoload/ctrlp.vim b/autoload/ctrlp.vim
index d2ba69a..b1fe859 100644
--- a/autoload/ctrlp.vim
+++ b/autoload/ctrlp.vim
@@ -2305,7 +2305,7 @@ fu! s:lastvisual()
 	let cview = winsaveview()
 	let [ovreg, ovtype] = [getreg('v'), getregtype('v')]
 	let [oureg, outype] = [getreg('"'), getregtype('"')]
-	sil! exe 'norm! \<C-U>gv"vy'
+	sil! norm! gV"vy
 	let selected = s:regisfilter('v')
 	cal setreg('v', ovreg, ovtype)
 	cal setreg('"', oureg, outype)
```

**Comment by mattn** [comment]
Well, I'll push this change now. Please let me know if this change also broken.

**Comment by GabeIsman** [comment]
@mattn That appears to have fixed the problem! Thanks.
