### ISSUE TITLE
Add an option to disable changing the cursor

### ISSUE THREAD

**Issue by logarytm** [ctrlpvim/ctrlp.vim#366]
I turned off cursor blinking in my terminal emulator (Konsole), and disabled `guicursor` in `init.vim` (which since Neovim 0.2 also [affects the terminal cursor](https://github.com/neovim/neovim/commit/58422f17d8e7e5f2dcba099b8829e5d23554e980)).  Now whenever I use CtrlP, the cursor is changed to `_` and then restored to a block cursor, which turns on blinking—which is [annoying](http://www.jurta.org/en/prog/noblink), and I do not expect a text editor to mess with my console cursor.  Please add an option to disable changing the cursor.  Thank you.

**Comment by mattn** [comment]
I don't reproduce in vim8 (not neovim). And ctrlp.vim change the guicursor but restore original. Maybe it seems a bug of neovim.

https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L1002-L1009

**Comment by rotsix** [comment]
Plop, got same problem with neovim v0.2

**Comment by mattn** [comment]
anyone, did you file issue into neovim?

**Comment by jurisbu** [comment]
Unusable with neovim> 0.17 and konsole.

**Comment by mattn** [comment]
Anyone, did you file issue into neovim?

**Comment by Lenovsky** [comment]
They know the issue, [FAQ](https://github.com/neovim/neovim/wiki/FAQ) suggests the following:

> Note: some plugins like "ctrlp" override guicursor even when it is empty. To totally disable cursor updates, you can set VTE_VERSION="100".
But it would be better to fix the plugin: it should not modify guicursor if it is empty.

I guess they think this is a ctrlp problem ;)

**Comment by mattn** [comment]
Thank you for pointing link to the neovim's bug. Anyone could you please try this patch?

```diff
diff --git a/autoload/ctrlp.vim b/autoload/ctrlp.vim
index de60d77..2a8ae88 100644
--- a/autoload/ctrlp.vim
+++ b/autoload/ctrlp.vim
@@ -1006,7 +1006,9 @@ fu! s:KeyLoop()
 	wh exists('s:init') && s:keyloop
 		try
 			set t_ve=
-			set guicursor=a:NONE
+			if guicursor != ''
+				set guicursor=a:NONE
+			en
 			let nr = getchar()
 		fina
 			let &t_ve = t_ve
@@ -2009,7 +2011,7 @@ fu! s:bufnrfilpath(line)
 		if (a:line =~ '[\/]\?\[\d\+\*No Name\]$')
 			let bufnr = str2nr(matchstr(a:line, '[\/]\?\[\zs\d\+\ze\*No Name\]$'))
 			let filpath = bufnr
-		else
+		els
 			let bufnr = bufnr(a:line)
 			retu [bufnr, a:line]
 		en
@@ -2414,7 +2416,7 @@ fu! s:buildpat(lst)
 			let c = a:lst[item - 1]
 			let pat .= (c == '/' ? '[^/]\{-}' : '[^'.c.'/]\{-}').a:lst[item]
 		endfo
-	else
+	els
 		for item in range(1, len(a:lst) - 1)
 			let pat .= '[^'.a:lst[item - 1].']\{-}'.a:lst[item]
 		endfo
```

**Comment by mattn** [comment]
@Lenovsky Thank you for pointing link to the neovim's bug. fixed just now.
