### ISSUE TITLE
Async mode is quite buggy

### ISSUE THREAD

**Issue by LemonBoy** [ctrlpvim/ctrlp.vim#369]
It looks like #213 got merged without much testing...

* The documentation refers to `g:user_command_async` while the code respects `g:ctrlp_user_command_async`, no wonder nobody has noticed any bug ;)
* The job isn't stopped when the ctrlp prompt is closed. Adding a `job_stop` in `s:Close` isn't enough as the callback is gonna keep getting called even after the job is stopped if there's any content in the channel buffer.
* The file list is never updated even after the job has finished, you can probably force a redraw in the `close_cb` or something similar.

**Comment by mattn** [comment]
could you please send p-r?

**Comment by LemonBoy** [comment]
I'm not familiar enough with the code to be useful, I'm sorry :(

**Comment by mattn** [comment]
No prob. do not say sorry. :)
