### ISSUE TITLE
MRU doesn't update

### ISSUE THREAD

**Issue by synthmeat** [ctrlpvim/ctrlp.vim#371]
After #368 (some discussion [here](https://github.com/ctrlpvim/ctrlp.vim/commit/0677f471c007691ab3e3c5e41849a21d9529ee90)), MRU list doesn't update.

If I add `let g:ctrlp_types = ['fil', 'buf', 'mru']` to my `.vimrc`, it does work. However, this should work (by design) by default.

**Comment by mattn** [comment]
Ah, sorry. I notice my bug. Will fix soon.
