### ISSUE TITLE
make the input line at the top of ctrlp buffer

### ISSUE THREAD

**Issue by amosbird** [ctrlpvim/ctrlp.vim#374]
Is there a configuration that could achieve this?

**Comment by tacahiroy** [comment]
You can use `g:ctrlp_match_window` for that.
```vim
let g:ctrlp_match_window = 'top'
```

See `:h g:ctrlp_match_window` for further details.

**Comment by amosbird** [comment]
Um, I mean the `ctrlp_match_window` is still at the bottom but the input command line being at top of it.

**Comment by tacahiroy** [comment]
No, there is no options for that unfortunately.

**Comment by ChillerDragon** [comment]
Was that added during the last few years? :)
