### ISSUE TITLE
Commit "support plugin-local matcher" breaks search

### ISSUE THREAD

**Issue by tkonolige** [ctrlpvim/ctrlp.vim#375]
Commit #064bc6eb8546150d6cac477a06346ea62fe77d06 "support plugin-local matcher" breaks search for me. When I activate ctrl-p I just see one entry with the contents `0`.

**Comment by danarnold** [comment]
Same here. Rolling back to 019f20a6f280b875b3812ea4d03a4cf1647cd0d9 fixes the issue.

**Comment by EvanHahn** [comment]
I'm experiencing something like this as well. If it helps, I spun up a new Vagrant VM and ran the following commands on a completely new machine:

```sh
# install git and vim
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install git vim -y

# clone ctrlp
git clone 'https://github.com/ctrlpvim/ctrlp.vim.git'

# because it's my only vim plugin, I can symlink it to ~/.vim
ln -s ctrlp.vim/ ~/.vim

# go inside and verify: search stops working
cd ctrlp.vim/
vim  # search stops working here

# revert to an old commit where it works
git checkout 019f20a6f280b875b3812ea4d03a4cf1647cd0d9
vim  # search works here
```

**Comment by mattn** [comment]
Should be fixed in latest.
