### ISSUE TITLE
[Help] Setting up CtrlP to open when no files were specified

### ISSUE THREAD

**Issue by PratikBhusal** [ctrlpvim/ctrlp.vim#378]
Right now I am trying to setup CtrlP to open at a sub-folder inside my Programming-Projects folder. As of the making of this message, that sub-folder's name is the current year (2017). Below is what I have so far:

```
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") |CtrlP /Programming-Projects/strftime('%Y')|endif
```

It almost works. If i were to replace `strftime('%Y')` and hard-code in the year `2017` it works as expected; however, if I leave it as is I would get the following error:

> Error detected while processing VimEnter Auto commands for "*": E499: Empty file name for '%' or '#', only works with ":p:h": CtrlP /Programming-Projects/strftime('%Y')|endif

Obviously I could just keep it at 2017 and change the number at the beginning of a new year, but it would just be better for it to change automatically. If you have an idea on how to set it up, I would appreciate knowing about it.

**Comment by mattn** [comment]
```
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") |CtrlP /Programming-Projects/strftime('\%Y')|endif
```
Escape `%` with backslash.

**Comment by PratikBhusal** [comment]
I tried using your modification, but it does not seem to work as intended.Could you please re-open the issue? I may have found the issue, but I'm not too sure how to fix it. I did gvim -V9vim.log and found a couple lines that may indicate the problem:

```
Error detected while processing function ctrlp#init[6]..<SNR>67_SetWD[6]..ctrlp#setdir:
line    2:
E344: Can't find directory "C:/Programming-Projects/strftime('%Y')" in cdpath
Error detected while processing function ctrlp#init[6]..<SNR>67_SetWD[6]..ctrlp#setdir:
line    2:
E472: Command failed
Error detected while processing function ctrlp#init[6]..<SNR>67_SetWD[6]..ctrlp#setdir:
line    2:
E580: :endif without :if: endif
Calling shell to execute: "cd /d "C:\Users\Pratik" && git ls-files -co --exclude-standard >C:\Users\Pratik\AppData\Local\Temp\VIoA43A.tmp 2>&1"
Error detected while processing function ctrlp#init[23]..ctrlp#syntax:
line    5:
E421: Color name or number not recognized: ctermfg=#1B1D1E>>> _
```

If my hunch is correct, CtrlP thinks that strftime('\%Y') is the actual name of the directory rather than what it should return (i.e 2017). Since it could not set it to be that directory, it automatically changed it to be my home directory.

**Comment by PratikBhusal** [comment]
> try exe "CtrlP " . strftime('\%Y')

I changed your suggestion a bit to match my situation:
`autocmd VimEnter * if argc() == 0 && !exists("s:std_in") |exe "CtrlP C:/Programming-Projects/" . strftime('%Y')|endif`

From the looks of things, it works as intended. Thank you!
