### ISSUE TITLE
updating ctrlp breaks search. even with no plugins installed beside it

### ISSUE THREAD

**Issue by bidah** [ctrlpvim/ctrlp.vim#379]
calling ctrlp give me this quickfix window
```
0
 prt  path  <mru>={ files }=<buf> <->
```

any ideas?

**Comment by mattn** [comment]
Should be fixed in latest.

**Comment by bidah** [comment]
The problem happened yesterday when I updated to the latest version. Updated today again and its the same issue. 😢

**Comment by mattn** [comment]
Still have issue!?

**Comment by ali-hs** [comment]
This issue still exists

**Comment by mattn** [comment]
How to reproduce this?

**Comment by alvan** [comment]
Have this issue too.

**Comment by mattn** [comment]
please let me the way to reproduce.

**Comment by mattn** [comment]
What is your configuration for CtrlP?

**Comment by alvan** [comment]
@mattn 
My configuration for CtrlP:
`let g:ctrlp_map = '?'`

**Comment by mattn** [comment]
I got repro just now.

**Comment by mattn** [comment]
Should be fixed.

https://github.com/ctrlpvim/ctrlp.vim/commit/f74ef642c46e757619f0c70fd0246ff1463f5a9e

**Comment by alvan** [comment]
Cool!
It works great now!
Thank u @mattn
