### ISSUE TITLE
Empty the search prompt when ctrlp invoked

### ISSUE THREAD

**Issue by cdjkim** [ctrlpvim/ctrlp.vim#386]
I was wondering if it is possible to empty the previous search everytime I invoke ctrlp. 

Currently, the default setting seems that the preivous search is displayed when I invoke ctrlp, so I have to press backspace to delete all the characters before I can do a new search. 

Is there a way to have an empty search prompt every time ctrlp is invoked??

**Comment by mattn** [comment]
Type <kbd>CTRL</kbd>-<kbd>u</kbd>

**Comment by danielfoxp2** [comment]
Ok, but is it possible to not have this feature set? Because is not cool type `ctrl+u` every single time I invoke ctrlp.
