### ISSUE TITLE
CtrlP project switcher

### ISSUE THREAD

**Issue by thiderman** [ctrlpvim/ctrlp.vim#39]
I have a project called [ctrlp-project](https://github.com/thiderman/ctrlp-project). It's a simple project switcher that looks at either predefined directories with repositories or scans your $HOME for any top-level directory that contains git repositories. Once you've selected a project, it will immediately spawn a normal CtrlP in that project root, so you can split, vsplit or whatever with whatever file you are navigating to.

![It looks nice too](http://i.imgur.com/dDH4JEF.png)

It's *very* useful and I've been using it daily for over a year. No more quitting vim or navigating with a `:cd` or `:lcd` with a thousand `../../` or similar! At this computer (which I've had since January) I've done more than 500 switches according to my cachefile.

I was thinking of making it more production grade:
* Cross platform (it's semi-UNIX specific right now)
* Documentation (README and `doc/`)
* Support for more VCSs than just git

I feel like this functionality fits very well in the core of a fuzzy switcher. I would love to spend some time to actually make it better and prepare a pull request. Would this be something that could be interesting to integrate into this project?

**Comment by ludovicchabant** [comment]
Yeah I agree, this can stay as an extension (I actually have [something similar myself](https://bitbucket.org/ludovicchabant/dotfiles/src/6c1ae937ad66dcafcf6da1731fde5a4f54f02c02/vim/autoload/ctrlp/projectjump.vim?at=default)). Besides, it would kinda duplicate functionality with the existing `bookmarkdir` extension if we merged something like that in the core codebase.
