### ISSUE TITLE
How to bind control+backspace?

### ISSUE THREAD

**Issue by ecly** [ctrlpvim/ctrlp.vim#392]
I'm trying to rebind the defaults for opening a selected file in a new split. In vim I normally define backspace as and it seems to be similar in ctrlp from what I read in

```
:h ctrlp_prompt_mappings
```

where `<bs>` is used. I've tried various variations but can't get it working with Control+Backspace.

Here's what I have right now, which works fine for my vertical splits but not horizontal.

```
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-bs>', '<2-LeftMouse>'],
    \ 'AcceptSelection("v")': ['<c-\>', '<RightMouse>'],
    \ }
```

**Comment by mattn** [comment]
vim on terminal? or GUI?

**Comment by ecly** [comment]
@mattn vim in terminal

**Comment by mattn** [comment]
AFAIK, vim in terminal can't map keys CTRL-BS.

**Comment by ecly** [comment]
@mattn Damn - I'll just try seeing if I can get a CTRL-BS bind working with Vim in general when I get home, and close the issue if it simply can't be done.

**Comment by ecly** [comment]
Alright, can't seem to get a CTRL-BS bind working for anything in vim, so I'll assume it just can't be done and close this for now. Thanks anyways!
