### ISSUE TITLE
How to show more modes in status line?

### ISSUE THREAD

**Issue by daniel2887** [ctrlpvim/ctrlp.vim#393]
Maybe I missed this in the docs, so any help is appreciated.
When I open CtrlP, the status line shows 3 modes. In my case what it shows exactly is:
` regex bkd files buf     <->`

So there are 3 modes visible: bookmarked dirs, files, and buffers. I then have the option to cycle through more modes.

My questions are,
1) Is there's a way to show more of the available modes? Feels like only a small part of my display's horizontal realestate in the status bar area is being used.
2) Is there a way to avoid abbreviating modes? For example, instead of "bkd", show the full "bookmarked dirs" label.

**Comment by tacahiroy** [comment]
Unfortunately, there is no options provided to achieve that.

**Comment by tacahiroy** [comment]
No further action required. closing
