### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by lifecrisis** [ctrlpvim/ctrlp.vim#396]
It looks like the documentation for `:CtrlPCurWD` and `:CtrlPCurFile` could be incorrect.  When the variable `g:ctrlp_working_path_mode` is mentioned, shouldn't the value *not* be empty here?

For example:

```text
                                                                *:CtrlPCurFile*
:CtrlPCurFile
    This acts like |:CtrlP| with |g:ctrlp_working_path_mode| = '' and ignores
    the variable's current value.
```

Shouldn't the variable mentioned here have the value `'c'`?

**Comment by tacahiroy** [comment]
You are right.
* `:CtrlPCurFile` behaves the same with `g:ctrlp_working_path_mode = 'c'`
* `:CtrlPCurWD` behaves the same with `g:ctrlp_working_path_mode = 'd'`

**Comment by tacahiroy** [comment]
Thanks for pointing that out.
