### ISSUE TITLE
Cursor shape changes after using ctrlp

### ISSUE THREAD

**Issue by paulo** [ctrlpvim/ctrlp.vim#404]
I use iTerm2 with a vertical-bar cursor. After opening a ctrlp window, the cursor changes to block shape and stays that way, even in iTerm2, after leaving vim.

Pretty straightforward to replicate, but I can describe the steps if needed.

**Comment by rtucek** [comment]
@prccaraujo neovim user with v0.2?

Put this in your init.vim:
`set guicursor=`
And start neovim like so: `VTE_VERSION="100" nvim`.

However, with vim, you shouldn't have the issue at all.

See this https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal

**Comment by prccaraujo** [comment]
Thank you for answering @rtucek. 

That's a nice workaround, however, it doesn't fix the behaviour of ctrlp for nvim, it just disables cursor updates, which is not ideal.

I stopped using ctrlp and I'm using fzf instead for now. I'll try to fix the issue and make a PR for it when I have the time.

Cheers

**Comment by sipior** [comment]
Just wanted to add that I've a similar problem to @prccaraujo, although running with neovim 0.2.2 on Ubuntu 18.04, and *only* when running neovim inside tmux. Using both "set guicursor=" and VTE_VERSION="100" mitigations, the problem remains. ctrlp is the only plugin that seems to trigger this behaviour, near as I can tell. Doesn't seem to be affected by changing TERM either.

I've also tried setting the autocmd recommended in the neovim FAQ you reference, but to no avail.

**Comment by jechols** [comment]
Same problem: neovim 0.2.2, Ubuntu 18.04, except instead of a funky cursor I end up with spurious "q"s all over the screen until I close the tmux pane entirely and restart neovim.  I'd love a way to just not have cursor changes happen from the plugin at all.

**Comment by kormat** [comment]
I finally managed to track down the issue.

https://github.com/ctrlpvim/ctrlp.vim/blob/ebc568c3992d9002d1d35b85737dfa0d9ce70d9f/autoload/ctrlp.vim#L116-L118
`gcr` is an alias for `guicursor`. `s:Open()` iterates over `s:glbs` and sets each option. The logic needs to be changed that gcr isn't set if `guicursor` is empty (the same logic that is already done in `s:KeyLoop()`).

**Comment by sipior** [comment]
Thanks for hunting that down, @kormat!

**Comment by paulo** [comment]
This is quite inactive, I'm closing it. Thanks everyone for the help.
