### ISSUE TITLE
Files with the same name but different case are excluded from results

### ISSUE THREAD

**Issue by anowlcalledjosh** [ctrlpvim/ctrlp.vim#416]
Repro:

1. have two files with the same name but different case in the same directory, e.g. `foo` and `FOO`
2. open one file
3. try to use ctrlP to open the other
4. you can't – just get `== NO ENTRIES ==`

I have no special ctrlP config in my vimrc.

**Comment by mattn** [comment]
I can't reproduce.

![2eb29861421a297c](https://user-images.githubusercontent.com/10111/38232272-41c5712e-3751-11e8-8a67-6891bb34a340.png)

**Comment by mattn** [comment]
Hmm, foo and FOO is displayed but can't mark the buffer correctly.

**Comment by tacahiroy** [comment]
@mattn i've found the culprit for this issue and have fixed here: 05bc7b6
however, my solution could be changing current behaviour, so i wanted you to double check if this fix is ok.

**Comment by mattn** [comment]
Good catch. I'll look this.

**Comment by mattn** [comment]
LGTM. Merged https://github.com/ctrlpvim/ctrlp.vim/commit/4b9e7cac612902a25498cca49f13475fe1a821a4
