### ISSUE TITLE
Cannot use with fd

### ISSUE THREAD

**Issue by clozed2u** [ctrlpvim/ctrlp.vim#418]
I try to use [fd](https://github.com/sharkdp/fd) as `ctrlp_user_command` with no luck. Here what I set in my vimrc

```
let g:ctrlp_user_command='fd %s --type file --color never'
```

Any idea why this isn't working?

**Comment by tacahiroy** [comment]
may be your `fd` commad line is not valid?
Can you try this please:
```vim
let g:ctrlp_user_command ='fd --type file --color never "" %s'
```

```console
% fd --version
fd 6.0.0
```

**Comment by clozed2u** [comment]
@tacahiroy Thanks, it's work.
