### ISSUE TITLE
ignore patterns read from file

### ISSUE THREAD

**Issue by typekpb** [ctrlpvim/ctrlp.vim#44]
As far as I've learned, there is an option to ignore specific files/dirs/symlinks, via:

    let g:ctrlp_custom_ignore = {
      \ 'dir':  '\v[\/]\.(git|hg|svn)$',
      \ 'file': '\v\.(exe|so|dll)$',
      \ 'link': 'some_bad_symbolic_links',
      \ }

Not sure about the name of the property, but I'd like to have an option, where ctrlp plugin would read `.gitignore` file and ignore all those specified. Similar could be available for `.hgignore`

As I use git a lot and projects have already `.gitignore` file present with all content I don't care about.

**Comment by ludovicchabant** [comment]
You're looking for this: https://github.com/ludovicchabant/vim-ctrlp-autoignore
(you'll need the very latest CtrlP for it to work, as it uses new extension features)
See the FAQ in the Vim help for an explanation as to why it's using a new `.ctrlpignore` file, though, as opposed to re-using `.gitignore` or `.hgignore`.

**Comment by typekpb** [comment]
thanks a lot for plugin and reference!
