### ISSUE TITLE
Weird <bi></bi> after last update

### ISSUE THREAD

**Issue by CharlesGueunet** [ctrlpvim/ctrlp.vim#445]
Hello, 

i just updated Ctrlp after the #316  merge and since then I see weird tag around each element of the CtrlP window:

```
  >   6 <bi></bi>     <bn>{file1}</bn>                          <bp>./</bp>
  >   9 <bi>#</bi>    <bn>{file2}</bn>                          <bp>./</bp>
```

It does not prevent me to use the plugin.

Charles

**Comment by tacahiroy** [comment]
Setting filetype to ctrlp buffer resets conceal words.
Thanks for notifying the issue.
