### ISSUE TITLE
entering 'p' key within search causes error (vim-pasta)

### ISSUE THREAD

**Issue by peterdutton** [ctrlpvim/ctrlp.vim#447]
Hi,

Since I recently updated ctrlp.vim I have noticed that if I type anything with the 'p' key when searching, I get the following error:

`
Error detected while processing function <SNR>73_NormalPasta:
line    2:
line    6:
E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
`

After some searching I think that the error is a conflict with the '[vim-pasta](https://github.com/sickill/vim-pasta)' plugin (which I also use). 
Disabling that plugin gets rid of the issue, however there haven't been any changes in that plugin for quite a while.
Any ideas how to resolve this, or how I could debug further?

Thanks

**Comment by mattn** [comment]
It's not a bug of CtrlP. CtrlP's buffer is not motifiable but the p (NormalPasta) is trying to modify the CtrlP's buffer. Please report it to vim-pasta.

**Comment by peterdutton** [comment]
Actually I think this is related to #316, which appears to have been recently merged. Before there was a filetype in CtrlP, vim-pasta did not attempt to modify the buffer. 
In case anyone else has this problem you can get around it by adding the new CtrlP filetype into the disabled filetypes for CtrlP, e.g:
`let g:pasta_disabled_filetypes = ['ctrlp']`

Thanks
