### ISSUE TITLE
CtrlP filetype issue

### ISSUE THREAD

**Issue by peterdutton** [ctrlpvim/ctrlp.vim#453]
The recent commit [e66b5b5](https://github.com/ctrlpvim/ctrlp.vim/commit/e66b5b50e5c539354813e2ecac6fb75a2121e29e) - which intended to fix case #451 - doesn't appear to be working as expected for me. 

Each time CtrlP is invoked, the code concatenates another time to the file type, for example:

on first invocation `&ft` = 'ctrlp'
second invocation `&ft` = 'ctrlp.ctrlp'
third invocation `&ft` = 'ctrlp.ctrlp.ctrlp'

Is this the intended behaviour?

Thanks

**Comment by mattn** [comment]
@tacahiroy can you handle this issue?

**Comment by tacahiroy** [comment]
@mattn am thinking to fix this with this way:
* type = coretypes or builtin extensions
  * ctrlp
* filetype = emtpy
  * ctrlp
* filetype != empty (means `&filetype` is set by a ctrlp.vim's extension)
  * ctrlp + . + filetype

Do you think it's ok?

**Comment by mattn** [comment]
Sounds good to me.

**Comment by peterdutton** [comment]
Looks good - thanks!
