### ISSUE TITLE
buffertag syntax highlighting not working

### ISSUE THREAD

**Issue by shyun3** [ctrlpvim/ctrlp.vim#463]
![image](https://user-images.githubusercontent.com/37260523/43056793-1779061c-8df3-11e8-957a-593b5615c6a4.png)

Only after pressing F5 do the colors show up. The highlighting is reset with every use of the buffer tags.

**Comment by ezequielv** [comment]
Hi, @shyun3. I have recently started using `ctrlp.vim` and have also been hit with this issue. I have implemented a fix for it, which seems to have resolved it for me. Please see the branches:

* https://github.com/ezequielv/ctrlp.vim/tree/dev_ezequielv-fix-issue_upstream-0463-nosyntaxhl_when_opening-01_01-upstream_01 : for a branch that applies cleanly to the current upstream's `master`;
* https://github.com/ezequielv/ctrlp.vim/tree/dev_ezequielv-fix-issue_upstream-0463-nosyntaxhl_when_opening-01_01 : for a branch that includes other fixes I've made for `vim-7.0` (upstream's `master` seems broken for `vim-7.0` at the moment, and I'll probably create the issues and pull requests some time to bring this plugin back to being `vim-7.0` compatible);

Please let me know if this works for you. I've tested this branch on `vim-8.1` (recent patch level) on Mac OS X, `neovim` (latest dev and `0.3.1-stable`) on Linux (amd64), `vim-7.0` (just the branch `dev_ezequielv-fix-issue_upstream-0463-nosyntaxhl_when_opening-01_01`) on Linux (amd64), and various other `vim` releases (including `7.4.52`, `7.4.1988`, `8.1.347`) on Linux (amd64).

I'm creating a pull request, too, to try and get this merged for everybody's benefit.

**Comment by shyun3** [comment]
I tried the branch for `vim-8.1` and it seems to work
