### ISSUE TITLE
Question: what's wrong with my custom open function?

### ISSUE THREAD

**Issue by slmjkdbtl** [ctrlpvim/ctrlp.vim#473]
the code responsible for opening files in my `g:ctrlp_open_func` is this:
```viml
exec 'edit ' . fnameescape(fnamemodify(a:line, ':p'))
```

but I noticed the files I opened with this open func sometimes lose its filetype when switching buffers (`set ft?` returns nothing the files appears to be modified), what could possibly go wrong?

edit:
I was originally doing custom open func just to customize the behavior when opening directories, now I managed to do that by  `autocmd BufEnter` and not having to use the custom open func by ctrlp. But still like to know why the code above would cause the problem.

**Comment by mattn** [comment]
Can you show a way to reproduce reliably?

**Comment by slmjkdbtl** [comment]
@mattn Sorry, it's been a while, I'm not using ctrlp now and forgot if I solved this or not, I guess this could be closed for now.
