### ISSUE TITLE
Error when entering 'p' or 'P' letter in search field.

### ISSUE THREAD

**Issue by alex-shamshurin** [ctrlpvim/ctrlp.vim#475]
![2018-08-27 12 26 39](https://user-images.githubusercontent.com/1595209/44652466-9b743a00-a9f4-11e8-8e11-ffbd5cc0caee.png)

Seems it's like trying to paste from buffer (while being in insert mode)

**Comment by mxie** [comment]
I am also experiencing the same issue!

**Comment by mxie** [comment]
Poked around a bit and found #466 and #447 with some ideas and a workaround if you happen to be having vim-pasta. I should be good now.

**Comment by alex-shamshurin** [comment]
Hmm, I forgot what vim-pasta actually do. Seems it's better to disable it

**Comment by alex-shamshurin** [comment]
Thanks a lot
