### ISSUE TITLE
help installing ctrlp

### ISSUE THREAD

**Issue by gurungrahul2** [ctrlpvim/ctrlp.vim#481]
I can't install ctrlp using the installation documentation, actually i can't find the ~/.vim folder, i am on Ubuntu bionic and I had installed latest vim using apt-get. Please someone assist me.

**Comment by cameck** [comment]
https://askubuntu.com/questions/400490/no-vim-folder-in-ubuntu-13-04-where-to-go-for-it

**Comment by gurungrahul2** [comment]
Thanks man, you sorted it out.
