### ISSUE TITLE
Buffer view displays "[No Name]" when directory path contains [ or ]

### ISSUE THREAD

**Issue by sim590** [ctrlpvim/ctrlp.vim#487]
Issue is similar to #323, but the cause is not the same. Issuing the following
shell command and hitting `C-pC-f` causes the issue:

```sh
$ mkdir [foo]
$ touch '[foo]'/{bar,baz}
$ vim -u <(<<< "set nocompatible
    let &rtp = '~/.vim/plugged/ctrlp.vim,' . &rtp

    filetype plugin indent on
    syntax enable") '+e ~/[foo]/bar' '+e ~/[foo]/baz'
```

**Comment by tacahiroy** [comment]
reproduced. I'll look into it.

**Comment by tacahiroy** [comment]
@sim590 I've fixed the issue in fix-487 branch. Can you please check if it works ok.

**Comment by sim590** [comment]
@tacahiroy The fix seems good after a manual test on my end.

**Comment by tacahiroy** [comment]
@sim590 Thanks for confirming that. I've just merged my fix to the master branch.
