### ISSUE TITLE
What is the target directory in g:ctrlp_user_command?

### ISSUE THREAD

**Issue by kshenoy** [ctrlpvim/ctrlp.vim#490]
[The documentation](https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L307) says to use `%s` instead of the target directory but it doesn't explain what the target directory is. 

My understanding is that if a file is loaded in a buffer, CtrlP tries to find the root marker relative to that file (by working upwards from the directory the file is located in) and `%s` is the directory where the root marker is located at. Is this correct? If not, is it related to the root marker in any way?

**Comment by allopislozano** [comment]
I guess that the file in %s depends on ctrlp_working_path_mode

**Comment by kshenoy** [comment]
@allopislozano That makes sense. Thanks. I'll submit a PR updating the doc.
