### ISSUE TITLE
on_type extension function

### ISSUE THREAD

**Issue by drozdowsky** [ctrlpvim/ctrlp.vim#494]
Is it possible to write extension that doesn't show anything on init but it starts executing something on type?
From what I can see most extensions cache everything on init and then the accept narrows down the  search.
I for example want to use grep -r in PWD and I want it to be lazy.

Thanks

**Comment by tacahiroy** [comment]
AFAIK, there's no API to implement that kind of feature unfortunately.

**Comment by drozdowsky** [comment]
I looked into code and I think you are right, lets close this one
