### ISSUE TITLE
Search a file by it's content

### ISSUE THREAD

**Issue by BigfootN** [ctrlpvim/ctrlp.vim#504]
Hello,

I don't know if this functionality exists, but I would like to know if one can find a file by it's content ?

For example if I have a file `foo` :

```
Some text
```

And an other file `bar`:

```
Some other text
```

If I search  for example `other` it would then return the file `bar`.

Thank you very much in advance for any help.

**Comment by mattn** [comment]
CtrlPLine? or find file which contains the typed text?

If seconds: https://github.com/mattn/ctrlp-swoop/

please note that this plugin possibly make CPU utilization to 100%

**Comment by BigfootN** [comment]
Thank you for your quick response.

You answered my question.

**Comment by sisrfeng** [comment]
In this aspect, ectrlp is wearker than LeaderF?
