### ISSUE TITLE
Please make clear what this project does.

### ISSUE THREAD

**Issue by santosh** [ctrlpvim/ctrlp.vim#512]
After reading the README, it's not clear what this project does. 

It is something like https://github.com/yegappan/mru? 

Or does it aids in autocompletion? Like the default <c-p> mapping does?

Or both? Please update the README accordingly.

**Comment by nguyenhai97** [comment]
It help you quickly search and open file in cwd or current project and more using fuzzy finder.

**Comment by santosh** [comment]
Closing this issue as part of personal housekeeping.
