### ISSUE TITLE
【question】what is mode() return when ctrlp start

### ISSUE THREAD

**Issue by tracyone** [ctrlpvim/ctrlp.vim#518]
when I  start a ctrlp window, what is mode() return?

**Comment by tacahiroy** [comment]
mode for the CtrlP window is `normal` mode and you cannot switch to other modes.

**Comment by tracyone** [comment]
@tacahiroy thx. How to tell vim that current window is ctrlp window?

**Comment by tacahiroy** [comment]
You can determine a window is a ctrlp window two ways:

1. &filetype is 'ctrlp'
1. bufname is 'ControlP'

**Comment by tracyone** [comment]
ok
