### ISSUE TITLE
Question: How to open in new tab when pressing enter

### ISSUE THREAD

**Issue by jrobinson52** [ctrlpvim/ctrlp.vim#519]
When a file is selected in the CtrlP finder pressing enter opens the file in the current window. How do I make it open in a new tab instead?

Thanks

**Comment by tacahiroy** [comment]
You can configure that with a variable `g:ctrlp_prompt_mappings` like this:
```vim
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<C-e>'],
    \ 'AcceptSelection("t")': ['<Cr>'],
}
```

See `h: g:ctrlp_prompt_mappings` for details.
