### ISSUE TITLE
'..' in prompt does not search parent directory

### ISSUE THREAD

**Issue by dsabsay** [ctrlpvim/ctrlp.vim#520]
When I enter CtrlP, sometimes I want to search in a different directory that is a sibling of my current directory.

The docs seem to indicate that entering `..` in the prompt will make CtrlP go up the directory tree one level. However, when I do this I just see `== NO ENTRIES ==`. In other words, it's not loading/indexing/searching the parent.

Is this a bug, or am I misinterpreting this `..` functionality?

**Comment by tacahiroy** [comment]
As explained in the doc you need to input `..` and press `<Enter>` to go up a directory.

```
d)  Submit two dots '..' to go upward the directory tree by 1 level. To go up
    multiple levels, use one extra dot for each extra level:

         Raw input    Interpreted as
         ..           ../
         ...          ../../
         ....         ../../../
```

**Comment by dsabsay** [comment]
@tacahiroy Ah got it. In my opinion, the wording does not indicate one must press `<Enter>`.

I was imagining that I could use `..` as part of a normal search (i.e. type `..myfile` to search for `myfile` in the parent directory. But that probably amounts to a feature request :-)
