### ISSUE TITLE
please consider tagging a new git release

### ISSUE THREAD

**Issue by anthraxx** [ctrlpvim/ctrlp.vim#522]
Hi,

It would be awesome to get a new git release so distro packages can make use of all the new code since 2016.

cheers

**Comment by anthraxx** [comment]
@mattn please can you tag a release? distro usage is still shipping versions from 2016

**Comment by tacahiroy** [comment]
@mattn I think it's good to tag the repo, still need to think about version and which version should be tagged, etc. though.

**Comment by mattn** [comment]
Okay, will do soon.

**Comment by mattn** [comment]
Well, last tag is `1.80` but this is not semantic version. What is proper next version? 1.81 or 2.0.0 ?

**Comment by anthraxx** [comment]
Whatever you prefer. If you don't want to follow strict semantic version. `1.81` is fine downstream but you can also bump it to `2.0` if there were major/breaking changes or such :cat: 
After that some semi regular tags would be super cool so distro packages get all your work distributed

**Comment by mattn** [comment]
I tagged 1.81. Thank you. If you still have issue, please file new issue.
