### ISSUE TITLE
Browsing between files with arrow keys

### ISSUE THREAD

**Issue by kviktor** [ctrlpvim/ctrlp.vim#534]
I'm using VIM 8.2 and I have these to open ctrlp
```
:map <c-t> :tabnew \| CtrlP<CR>
let g:ctrlp_map = '<c-f>'
```

However when I try to browse between the results with the arrow keys Vim simply inserts A/B/C/D (depending on which arrow key) into the existing/new empty tab and closes Ctrlp. Technically using Ctrl+J/K  still works but arrow keys used to work too.

**Comment by tacahiroy** [comment]
I'm guessing is that is caused by your terminal settings. Which OS and terminal emulator are you using?

**Comment by kviktor** [comment]
Oh, you are right, it works in gnome-terminal but not in alacritty.

**Comment by StephenTurley** [comment]
I've been having a similar issue with using arrow keys to browse the ctrlp file list. if I launch vim with `TERM=xterm vim` then I don't have the issue.
