### ISSUE TITLE
`g:ctrlp_match_func` doesn't look correct work.

### ISSUE THREAD

**Issue by nao0x2c6** [ctrlpvim/ctrlp.vim#553]
Thank you for the great plugin.

If `g:ctrlp_match_func` is set, the prefix will concatenate to the file names in the list repeatedly.

Example:

```vim
function! Hoge(items, str, limit, mmode, ispath, crfile, regex)
    return a:items
endfunction

let g:ctrlp_match_func = {'match' : 'Hoge' }
```
The above script means that any pattern matches any file.

Result:
![using-ctrlp_match_func](https://user-images.githubusercontent.com/15692034/93567138-27d16b00-f9c9-11ea-93ea-0efdf785254b.gif)

So, I cannot open the correct file but new file which has unnecessary prefix.

I use Vim v8.2.1704 on MacOS. Thanks.

**Comment by mattn** [comment]
You should use `copy`

```vim
function! Hoge(items, str, limit, mmode, ispath, crfile, regex)
    return copy(a:items)
endfunction
```

**Comment by nao0x2c6** [comment]
@mattn 
Thank you for fast response.

Actually, What I really want to do is to use `migemogrep` according to this article:
https://vim-jp.org/blog/2014/08/08/dropped-migemo-from-ctrlp-vim.html

Now, my code is:
```
function! MigemoMatch(items, str, limit, mmode, ispath, crfile, regex)
  let tmp = tempname()
  try
    if a:str =~ '^\s*$'
      return a:items
    endif
    call writefile(split(iconv(join(a:items, "\n"), &encoding, 'utf-8'), "\n"), tmp)
    return copy(split(iconv(system(
    \  printf('migemogrep %s %s',
    \    shellescape(a:str),
    \    shellescape(tmp))), 'utf-8', &encoding), "\n"))
  catch
    return []
  finally
    call delete(tmp)
  endtry
endfunction
let g:ctrlp_match_func = {'match' : 'MigemoMatch' }
```
But, ONE prefix still is concatenated to file names:
![one-prefix](https://user-images.githubusercontent.com/15692034/93570542-23f41780-f9ce-11ea-85ba-621cb98a7481.gif)

**Comment by mattn** [comment]
Please try this.

```vim
function! MigemoMatch(items, str, limit, mmode, ispath, crfile, regex)
  let tmp = tempname()
  try
    if a:str =~ '^\s*$'
      return copy(a:items)
    endif
    call writefile(split(iconv(join(a:items, "\n"), &encoding, 'utf-8'), "\n"), tmp)
    return split(iconv(system(
    \  printf('migemogrep %s %s',
    \    shellescape(a:str),
    \    shellescape(tmp))), 'utf-8', &encoding), "\n")
  catch
    return []
  finally
    call delete(tmp)
  endtry
endfunction
let g:ctrlp_match_func = {'match' : 'MigemoMatch' }
```

**Comment by nao0x2c6** [comment]
Ohhhh, completely worked. Thank you!!!

**Comment by mattn** [comment]
👍
