### ISSUE TITLE
How to create a custom ctrlp command

### ISSUE THREAD

**Issue by tami5** [ctrlpvim/ctrlp.vim#556]
Hay there, I'm trying so hard to create a ctrlp for a given list of dirs, which on enter I can cd into it.

It sucks that the documentation for ctrlp api is poor and it makes so diffcult to extend. 

Thanks

**Comment by tacahiroy** [comment]
am guessing is that you want to create the extension let you `cd` to the selected directory mebe?
If so see [readme.md](https://github.com/ctrlpvim/ctrlp.vim/blob/830fbc8845fed/readme.md) and a sample code found in the file.

**Comment by tami5** [comment]
Thanks a lot
