### ISSUE TITLE
ignore dir in most recent

### ISSUE THREAD

**Issue by ask1234560** [ctrlpvim/ctrlp.vim#560]
Hi

i want to ignore /tmp directory in most recent files, how can i do it.

i am using this, but its not working

```
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v\/tmp$',
  \ }

```

**Comment by hugoppp** [comment]
This is also a problem if you use CtrlP with vim-fugitive, because vim fugitive opens everything in a buffer. So after every commit, you have a ".git/COMIT_EDITMSG" in your MRU.

**Comment by ask1234560** [comment]
So what does `g:ctrlp_custom_ignore` do

**Comment by ask1234560** [comment]
```
" ignore patterns in CtrlPMRU
fun! Ctrlpmru()
    :!sed -i.bak -e '/\.git\//d' -e '/\/tmp\//d' "$XDG_CACHE_HOME/ctrlp/mru/cache.txt"
    :CtrlPMRU<CR>
endf
```
I fixed it by adding the above code in init.vim and `nnoremap <silent> <Leader>m :call Ctrlpmru()<CR>`.

**Comment by hugoppp** [comment]
Just tried it and it does not really work like I would like it to. It only filters out the lines after restarting vim, as the cache file is probably stored in memory.
