### ISSUE TITLE
Installation / About links broken

### ISSUE THREAD

**Issue by wolfisberg** [ctrlpvim/ctrlp.vim#569]
I'm trying to get ctrlp running in neovim but it won't work. So I wanted to check if there are some installation instructions and noticed that the following links are broken 404s.

* **About** in the side panel on the landing page of this git repo.<br>
http://ctrlpvim.github.com/ctrlp.vim
* **Installation** instructions at the bottom of the readme file<br>
http://ctrlpvim.github.com/ctrlp.vim#installation

**Comment by mattn** [comment]
Should be fixed now. Thank you.

https://github.com/ctrlpvim/ctrlp.vim/commit/f68f4d00b9c99d0d711bfde3b071f0dafd249901

**Comment by wolfisberg** [comment]
Thank *you*!
