### ISSUE TITLE
Is there anyway to directly pass search string to custom command each time search file?

### ISSUE THREAD

**Issue by benyaminl** [ctrlpvim/ctrlp.vim#580]
Hello, I wonder is that possible to make ctrlp search file directly from the output shown by the output of customer command each time we type? Thank you

**Comment by tacahiroy** [comment]
You mean you want to filter out the results of an arbitrary command you give each time against CtrlP, right? If so that is not supported now.

**Comment by benyaminl** [comment]
> 
> 
> You mean you want to filter out the results of an arbitrary command you give each time against CtrlP, right? If so that is not supported now.

Yes. Oh It's not supported now. Ok. Thank you, does it mean I need to close this issue?

**Comment by tacahiroy** [comment]
You can close this if it's clear now.
But I'm curious about your use cases if ctrlp had this functionality.

**Comment by benyaminl** [comment]
> You can close this if it's clear now. But I'm curious about your use cases if ctrlp had this functionality.

Well you can use using locate on linux or everything from voidtools on windows. It's much faster than globpath and fuzzy especially if the file list is very large, probably 100k file list.

**Comment by mattn** [comment]
https://github.com/mattn/ctrlp-everything

**Comment by benyaminl** [comment]
> https://github.com/mattn/ctrlp-everything

Is it a complement to this plugin or it's a seperate plugin? Please enlight me. Thank you
