### ISSUE TITLE
Can I use the 'lines' extension in CtrlPMixed?

### ISSUE THREAD

**Issue by samhed** [ctrlpvim/ctrlp.vim#582]
First of all, I must say that I love this plugin! Makes life so much easier. Thank you.

My `g:ctrlp_cmd` is set to `"CtrlPMixed"` currently. That makes CtrlP search for files, buffers and most recent files by default. To do a fuzzy search for lines I need to `Ctrl+f` to switch to lines-mode. Is there any way I can include lines in the mixed search?

**Comment by tacahiroy** [comment]
Unfortunately ctrlp.vim itself doesn't support that function. But I think it is possible to achieve that by creating a ctrlp.vim extension.

**Comment by samhed** [comment]
Okay, thanks for the reply. I have a different hotkey for lines search, that works fine for now.

**Comment by tacahiroy** [comment]
ok then closing it.
