### ISSUE TITLE
Can't go to function definition by CtrlPTag

### ISSUE THREAD

**Issue by hanfezh** [ctrlpvim/ctrlp.vim#583]
When I pull the latest commit [fff74986](https://github.com/ctrlpvim/ctrlp.vim/commit/fff74986c5439015cf5cc69cf2c6390a40fdd79f), it can't go to the selected function definition using `CtrlPTag`.

I tried *Vi 8.2 (Included patches: 1-905)* and *Neovim v0.5.0-dev*, neither can work. But it worked at commit [5b096681](https://github.com/ctrlpvim/ctrlp.vim/commit/5b096681427d2a130f348c7ca2327d3c33c2f6f6)

**Comment by mattn** [comment]
@IngoMeyer441  Can you handle this?

**Comment by IngoMeyer441** [comment]
Sorry, for breaking the tag accept function! :sweat: @hanfezh You mean `CtrlPBufTag` instead of `CtrlPTag`, didn't you?

This should be fixed with PR #584.

**Comment by mattn** [comment]
Closed by #584 
Please reopen if you still have issue

**Comment by hanfezh** [comment]
> CtrlPBufTag

Yes, it's `CtrlPBufTag` not `CtrlPTag`.
Thanks to @IngoMeyer441 and @mattn , it's fixed already.
