### ISSUE TITLE
highlight lost after changing colorscheme

### ISSUE THREAD

**Issue by gagara** [ctrlpvim/ctrlp.vim#585]
Steps to reproduce:
1. Run vim
2. Open CtrlP, make sure highlighting works fine
3. Change colorsheme. e.g. `:colorscheme evening`
4. Open CtrlP again

Actual Result:
No highlighting anymore

Expected Result:
Highlighting should work

Additional info:
vim version: `8.2`
ctrlp commit: `d9388d897`

**Comment by mattn** [comment]
Could you please try https://github.com/ctrlpvim/ctrlp.vim/pull/586 ?

**Comment by gagara** [comment]
works perfectly! thanks a lot!
