### ISSUE TITLE
Arrow keys broken in vim-8.2.4529

### ISSUE THREAD

**Issue by nsslh** [ctrlpvim/ctrlp.vim#593]
A few days ago, my up and down arrow keys stopped navigating the CtrlP selection window. Instead, they escape CtrlP, enter insert mode and insert a character (A).

After pulling my hair out for a while, I noticed another user reporting that this related to a recent vim update, in an old issue in the kie/ctrp.vim project: https://github.com/kien/ctrlp.vim/issues/794#issuecomment-1066746046

Downgrading to an earlier version of vim (8.2.3404) solves the issue. I don't like discarding security updates, so I'll live with Ctrl-j and Ctrl-k for navigation for now.

I'm using Fedora FC35 (Gnome), with term=gnome-256color.

**Comment by mattn** [comment]
It should be fixed in https://github.com/vim/vim/commit/bbf84e2737daf3479e059dc7e7da0c50a07a4bf4

**Comment by samhed** [comment]
Nice. Can confirm that it now works in vim 8.2.4579 on Fedora 35.

**Comment by nsslh** [comment]
Agreed, thanks.
