### ISSUE TITLE
Is there a limit to the number of files scanned when using user command? 

### ISSUE THREAD

**Issue by ydzhou** [ctrlpvim/ctrlp.vim#600]
My `CtrlP` setup to use `fd` to scan files.

When I search `vimrc` in my home directory, those more unrelated results show up but not the actual `dotfiles/vim/vimrc`
```
>   Downloads/Iosevka/Iosevka Term Bold Nerd Font Complete Mono.ttf
>   Downloads/Iosevka/Iosevka Term Oblique Nerd Font Complete.ttf
>   Downloads/Iosevka/Iosevka Medium Nerd Font Complete Mono.ttf
>   Downloads/Iosevka/Iosevka Term Medium Nerd Font Complete.ttf
>   Downloads/Iosevka/Iosevka Term Light Nerd Font Complete.ttf
```

Here is my setup
```
let g:ctrlp_map = '<leader>/'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_custom_ignore = {
            \ 'dir': '\.git$\|\.hg$\|\.svn$\|Library$\|Applications$\|Movies$\|Pictures$\|Music$\|tmp$',
            \ 'file': '\.zip$\|\.so$\|\.o$\|\.obj$\|\.class$\|\.DS_Store$'
            \}
let g:ctrlp_match_window = 'bottom,order:btt,min:5,max:30,results:30'
if executable('fd')
    let g:ctrlp_user_command = 'fd --type f --color never "" %s'
endif
let g:webdevicons_enable_ctrlp = 1
let g:ctrlp_by_filename = 0
let g:ctrlp_use_caching = 0
let g:ctrlp_mruf_max = 0
let g:ctrlp_max_files = 0
let g:ctrlp_max_depth = 20
let g:ctrlp_user_command_async = 1
```
If I do not use user command `fd` to scan, it works.
If I use `fd` but change settings on `g:ctrlp_match_window` to be `bottom,order:btt,min:5,max:30,results:2000`, it also works.

That's why I am wondering if there is a limit on how many scanned files `CtrlP` can read from an external scanner. Do you have any thought?

**Comment by ydzhou** [comment]
Interesting. If file is not loaded due to limit of `g:ctrlp_max_files`, why can I see them if I keep typing more characters?

**Comment by mattn** [comment]
rendering become heavily when too many files given. So I added code to omit lines over the limit. So you can get matched item if you type some.

**Comment by ydzhou** [comment]
Can you point me to the code?
How do you think about making this as an option? I can help with the code change.

**Comment by mattn** [comment]
https://github.com/ctrlpvim/ctrlp.vim/commit/628958ecb21046706c108d5a1aa2cc320438bf25

**Comment by ydzhou** [comment]
I think I find out the root cause why more relevant files are shown up. Can you take a look at the PR?

**Comment by ydzhou** [comment]
I understand `compare_lim` is to avoid CtrlP low performance on large directory. I think I can come up with another PR to improve this by not limiting the max number of files to sort.

The [code](https://github.com/ctrlpvim/ctrlp.vim/blob/8150fdd845a8c26326ceb9418d054370863e826c/autoload/ctrlp.vim#L400) for sorting first readout is using levenshtein distance, which is performance draining especially if file path is deep.

I think we can replace this sorting with more dumb comparison, maybe a hamming distance? That will make the performance much better.

**Comment by mattn** [comment]
closable?

**Comment by ydzhou** [comment]
Yeah please
