### ISSUE TITLE
Problem using ctrlp_custom_ignore

### ISSUE THREAD

**Issue by lsiden** [ctrlpvim/ctrlp.vim#602]
I need better documentation explaining _ctrlp_custom_ignore_.  I put this in .vimrc but it had no effect:

`"let g:ctrlp_custom_ignore = { 'dir': '(__pycache__|venv|build)$' }`

It just takes a regular expression, right?

**Comment by tacahiroy** [comment]
With basic Vim's regexp the configuration would be like either of examples below:
```vim
let g:ctrlp_custom_ignore = { 'dir': '\v(__pycache__|venv|build)$' }
```
or
```vim
let g:ctrlp_custom_ignore = { 'dir': '\(__pycache__\|venv\|build\)$' }
```

If none of them works can you show me all ctrlp related configs in your vimrc please.
