### ISSUE TITLE
"Argument must be positive: cmdheight=0"

### ISSUE THREAD

**Issue by nedbat** [ctrlpvim/ctrlp.vim#611]
I am using the latest code, and when switching files, I get:
```
Error detected while processing function <SNR>141_AcceptSelection[27]..ctrlp#acceptfile[17]..<SNR>141_PrtExit[4]..<SNR>141_Close:
line    1:
E487: Argument must be positive: cmdheight=0
```
I'm on MacVim:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 25 2022 08:23:03)
macOS version - x86_64
Included patches: 1-65
```

**Comment by nedbat** [comment]
Is it an effect of pull request #610 ?

**Comment by mattn** [comment]
Thanks your report. fixed.

**Comment by nedbat** [comment]
Hmm, I updated to get that commit, and still see the error message.

**Comment by nedbat** [comment]
Which makes sense, since the new code makes the old change if vim is new enough, and I am running a new vim.  Was the condition meant to be inverted?

**Comment by mattn** [comment]
```
echo has('patch-9.0-0015')
```
what result do you get?

**Comment by nedbat** [comment]
`1`

**Comment by mattn** [comment]
Ah, sorry.
```
echo has('patch-9.0.0015')
```
Please do again.

**Comment by mattn** [comment]
I fixed in last change. please update.

**Comment by nedbat** [comment]
Yay, it works! <3
