### ISSUE TITLE
Cannot invoke CtrlP with Remapped Key

### ISSUE THREAD

**Issue by JerromyCh** [ctrlpvim/ctrlp.vim#614]
I am a beginner of Vim user. I pasted such commands into .vimrc to learn the configuration of Vim.

      let g:ctrlp_map =  '<c-p>'
      let g:ctrlp_cmd = 'CtrlP'

By using ":nmap", I can see the key binding as <C-P>. However, I cannot invoke the CtrlP by pressing the "ctrl+p" key combo.
Please guide me on this. Thanks!

**Comment by JerromyCh** [comment]
I have found the solution. 

      let g:ctrlp_map =  '<c-p>'

Should be 

      let g:ctrlp_map =  '<C-p>'

And I can invoke the CtrlP by pressing the "ctrl+p" key combo.

**Comment by tacahiroy** [comment]
Interesting, because CtrlP is successfully started in either way in my environment. But yes, you already resolved the issue, so that's ok though.
