### ISSUE TITLE
Help configuring ctrlp.vim in Neovim with lazy.nvim

### ISSUE THREAD

**Issue by FMGordillo** [ctrlpvim/ctrlp.vim#618]
Sorry if this is a noob question

I've started with this as a boilerplate for my editor: https://github.com/nvim-lua/kickstart.nvim
I don't get how variables are set in this environment

`let g:ctrlp_custom_ignore = '\v[\/]\(node_modules|dist)$'`

Does anyone have experience with it? If so, how to do it?
TIA!

**Comment by jonahfang** [comment]
This is my config:

```
return {
  'ctrlpvim/ctrlp.vim',
  config = function()

    local keymap = vim.keymap -- for conciseness
    keymap.set('n', 'zp', "<cmd>CtrlP<cr>", {silent = true})

    vim.cmd([[
      let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|media'
    ]])

  end,
}
-- EOP

```
