### ISSUE TITLE
Custom working directories question

### ISSUE THREAD

**Issue by gonzaloserrano** [ctrlpvim/ctrlp.vim#70]
Hi guys!

I'm using ctrlp to program some PHP projects that follow the following structure, more or less:
```
/company-project
/company-project/app/
/company-project/app/config
/company-project/random-directory-1
/company-project/src
/company-project/random-directory-2
/company-project/vendors/
/company-project/vendors/random-vendor-1
/company-project/vendors/random-vendor-2
/company-project/vendors/company
/company-project/vendors/random-vendor-3
/company-project/vendors/random-vendor-4
/company-project/vendors/symfony
/company-project/vendors/random-vendor-5
/company-project/vendors/random-vendor-6
/company-project/random-directory-3
/company-project/web
```

Ideally i'd like ctrlp to index the only following directories:
```
/company-project/app/config
/company-project/src
/company-project/vendors/company
/company-project/vendors/symfony
/company-project/web
```

There is a .git directory inside ```/company-project``` and then there are .git directories inside every directory inside ```vendors``` e.g. in ```/company-project/vendors/any-vendor``` since they are downloaded with the composer php dependency manager.

I've thought about adding a ```.ctrlp```file inside the directories that interest me and then adding it to the ```g:ctrlp_root_markers``` var but the documentation says that these are additional markers and i think the .git ones inside the vendors would screw the whole thing.

Do you think this can be solved with some configuration tips somehow?

Thanks!

**Comment by tacahiroy** [comment]
Apparently, there is no options to specify inverse of ignore files/dirs.
If you can have the project specific root marker in the project root, this would work for you:
```vim
  let g:ctrlp_user_command = {
    \ 'types': {
      \ 0: ['.company_proj', 'cd %s && find . -type f \( -path ./app/config/\* -o -path ./src/\* -o -path ./vendors/company/\* -o -path ./vendors/symfony/\* -o -path ./web/\* \)' ],
      \ 1: ['.git/', 'cd %s && git ls-files . -co --exclude-standard'],
    \ }
  \ }
```
To enable this configuration, you need to create a file named `.company_proj` in the project root.

I guess you use Git, SVN or Hg etc. to manage your project, so you've already configured `g:ctrlp_user_command` to list the project files. Therefore, the project specific configuration needs to be prior to these VCS configurations like above.

I don't think this is the best approach, however, no idea any other ways to do that atm :/

**Comment by gonzaloserrano** [comment]
Hey @tacahiroy thanks a lot, that worked pretty well!

I just added an extra option to the ```find```command to avoid listing the vendors of vendors (since sometimes i need them so i can execute its tests etc) with something like ```-not -path "*/vendor/*/vendor/*"```.

So thanks again!

p.s i changed ```vendors```for ```vendor``` in my posts in case any PHP developer reads this ;)

**Comment by tacahiroy** [comment]
np :)
Closing.
