### ISSUE TITLE
BookmarkDir broken

### ISSUE THREAD

**Issue by Konfekt** [ctrlpvim/ctrlp.vim#71]
As soon as a character is typed after `:CtrlPBookmarkDir`,  the tabulator space `  ` between the folder and the bookmark title becomes a litteral `\t` that and joins the bookmark path and title. 

This is on Linux, Vim 7.4.560

**Comment by ludovicchabant** [comment]
I don't understand... `:CtrlPBookmarkDir` doesn't take any arguments, AFAIK?

**Comment by Konfekt** [comment]
Ahhh.. I am sorry. I meant the search box in thr bookmarked dirs, that's where the Text is entered.

**Comment by Konfekt** [comment]
So, by
```
fu! s:parts(str)
let mlist = matchlist(a:str, '\v([^\t]+)\t(.*)$')
retu mlist != [] ? mlist[1:2] : ['', '']
endf
```
the `\t` is used as separator.

**Comment by Konfekt** [comment]
By the way, this also holds for all other  `:CtrlPChanges/Quickfix...`

**Comment by Konfekt** [comment]
I am sorry, the cluprit is `https://github.com/FelikZ/ctrlp-py-matcher`

**Comment by Konfekt** [comment]
However, the problem seems to be that
```
    " +- a:mmode  : The match mode. Can be one of these strings:
    " |             + "full-line": match the entire line.
    " |             + "filename-only": match only the filename.
    " |             + "first-non-tab": match until the first tab char.
    " |             + "until-last-tab": match until the last tab char.
```
is not correctly passed to
```
let g:ctrlp_match_func = { 'match': 'Function_Name' }
```
Could you verify that?

**Comment by Konfekt** [comment]
Well, since it works just fine with `cmatcher` instead of `py-matcher` supposedly that's a `pymatcher` issue.

**Comment by ludovicchabant** [comment]
Yeah, it looks like it's correctly passing the mode anyway: https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L498
And AFAICT `pymatcher` is only checking for one type of mode: https://github.com/FelikZ/ctrlp-py-matcher/blob/master/autoload/pymatcher.vim
