### ISSUE TITLE
In *some* situations, CtrlP sets soft-wrapping on or fails to restore the `wrap` state

### ISSUE THREAD

**Issue by jeetsukumaran** [ctrlpvim/ctrlp.vim#75]
To replicate:

1. Ensure that soft-wrapping is off: `set nowrap` in `.vimrc`
2. Start Vim without any files (`$ vim`).
3. Run `:CtrlP` and select a file for opening. `wrap` will still be false.
4. Run `:CtrlP` again and select another file. `wrap` will now be on.

Alternatively:

1. Ensure that soft-wrapping is off: `set nowrap` in `.vimrc`
2. Open any file for editing in Vim.
3. Run `:CtrlP` again and select another file. `wrap` will now be on.

It appears that the two conditions required are: the current file must be any valid buffer (i.e., not `[No Name`]) and a file must be selected. The problem comes even with, e.g., `CtrlPBuffer`.

**Comment by jeetsukumaran** [comment]
It appears that this problem occurs because that the global `wrap` is at its default value (on), but the local option is set to off (`setlocal nowrap`). It seems that when CtrlP closes, it restores the wrap state to correctly with respect to the global wrap state, but this ignores/overrides/clobbers the local option. Perhaps CtrlP could check to see if the local option is set and use that in preference to the global one?

**Comment by mattn** [comment]
But you are saying below in the comment:

    1. Ensure that soft-wrapping is off: set nowrap in .vimrc

**Comment by jeetsukumaran** [comment]
Yes, sorry. I was wrong about that. I had that line commented out in my vimrc.

Modified replication:
- Make sure wrap is not set 
- Open any file for editing in Vim.
- `setlocal nowrap`
- Run :CtrlP again and select another file. wrap will now be on.

**Comment by mattn** [comment]
Sorry, i don't still understand what is your expected?

you set `nowrap` to local. so the another file you opened should be set `wrap` as same as default.

**Comment by jeetsukumaran** [comment]
Hi mattn,

Yes, but when I go back to the original file, it's wrap is now set.

**Comment by mattn** [comment]
Ok, could you please check below in the original file?

```
:verbose set wrap?
```

**Comment by jeetsukumaran** [comment]
Arrrgh. Mea culpa. Looks like another plugin is responsible. I thought it was CtrlP because it only happens when opening and then closing CtrlP. **So** sorry for the noise and trouble!

**Comment by jeetsukumaran** [comment]
p.s. *Great* plugin, and so glad that you folks are continuing to keep it alive. THANKS!

**Comment by mattn** [comment]
No problem! :)
