### ISSUE TITLE
getting system files when using ctrl-p

### ISSUE THREAD

**Issue by Shirty** [ctrlpvim/ctrlp.vim#99]
When not defining any options for ctrl-p in my vimrc the default behavior on one of my computers is this:

if I do ctrl-p in directory containing repo, i get all contents of directory but if i don't have a .svn or .git etc in my directory tree, ctrl-p starts searching my whole system! If i understand correctly it should be searching the current working directory.

The command CtrlPCurWD seems to work fine and does the correct thing,

if I let g:ctrl_working_path_mode to 'ra', nothing changes in the way it works.

g:ctrlp_working_path_mode doesn't seem to be set when I start vim. Is this normal? Should I be able to check if this is set when using :let g:ctrl_working_path_mode?

Wondering if this is the place I should be posting these questions? Should I use StackOverflow if i'm not sure about it being a bug?

**Comment by mattn** [comment]
don't you have `.git` or `.hg` or `.svn` in parent directory?

**Comment by Shirty** [comment]
When i do it doesn't search my whole file system, but my issue is when I don't have a repo dir in my parent directorys.  ctrl p searches my whole system when normally if i understand correctly it should search CWD or am I wrong in this?

**Comment by Shirty** [comment]
Somehow I had a .git file at c:\.git, no idea how I did that but my fault! So it's all working correctly now for me!
